// Generated by xls2ts.py
// DO NOT EDIT!
///<reference path="text.d.ts" />

declare module Data {
    class war_shop_card { 
        static get(id:number|string): any;
        static keys:number[];
    }
}
