-- Generated By protoc-gen-lua Do not Edit
local protobuf = import("net/protobuf/protobuf.lua")
pb_table = {}

REQUEST = protobuf.Descriptor();
pb_table.REQUEST_OPTION = protobuf.EnumDescriptor();
pb_table.REQUEST_OPTION_NO_REPLY_ENUM = protobuf.EnumValueDescriptor();
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD = protobuf.FieldDescriptor();
pb_table.REQUEST_METHOD_ID_FIELD = protobuf.FieldDescriptor();
pb_table.REQUEST_ARGUMENTS_FIELD = protobuf.FieldDescriptor();
pb_table.REQUEST_OPTIONS_FIELD = protobuf.FieldDescriptor();
REPLY = protobuf.Descriptor();
pb_table.REPLY_STATUS = protobuf.EnumDescriptor();
pb_table.REPLY_STATUS_OK_ENUM = protobuf.EnumValueDescriptor();
pb_table.REPLY_STATUS_ERROR_ENUM = protobuf.EnumValueDescriptor();
pb_table.REPLY_STATUS_DUPLICATE_ENUM = protobuf.EnumValueDescriptor();
pb_table.REPLY_SEQUENCE_NUMBER_FIELD = protobuf.FieldDescriptor();
pb_table.REPLY_STATUS_FIELD = protobuf.FieldDescriptor();
pb_table.REPLY_RESULT_FIELD = protobuf.FieldDescriptor();

pb_table.REQUEST_OPTION_NO_REPLY_ENUM.name = "NO_REPLY"
pb_table.REQUEST_OPTION_NO_REPLY_ENUM.index = 0
pb_table.REQUEST_OPTION_NO_REPLY_ENUM.number = 1
pb_table.REQUEST_OPTION.name = "Option"
pb_table.REQUEST_OPTION.full_name = ".Request.Option"
pb_table.REQUEST_OPTION.values = {pb_table.REQUEST_OPTION_NO_REPLY_ENUM}
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.name = "sequence_number"
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.full_name = ".Request.sequence_number"
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.number = 1
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.index = 0
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.label = 2
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.has_default_value = false
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.default_value = 0
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.type = 13
pb_table.REQUEST_SEQUENCE_NUMBER_FIELD.cpp_type = 3

pb_table.REQUEST_METHOD_ID_FIELD.name = "method_id"
pb_table.REQUEST_METHOD_ID_FIELD.full_name = ".Request.method_id"
pb_table.REQUEST_METHOD_ID_FIELD.number = 3
pb_table.REQUEST_METHOD_ID_FIELD.index = 1
pb_table.REQUEST_METHOD_ID_FIELD.label = 2
pb_table.REQUEST_METHOD_ID_FIELD.has_default_value = false
pb_table.REQUEST_METHOD_ID_FIELD.default_value = 0
pb_table.REQUEST_METHOD_ID_FIELD.type = 13
pb_table.REQUEST_METHOD_ID_FIELD.cpp_type = 3

pb_table.REQUEST_ARGUMENTS_FIELD.name = "arguments"
pb_table.REQUEST_ARGUMENTS_FIELD.full_name = ".Request.arguments"
pb_table.REQUEST_ARGUMENTS_FIELD.number = 4
pb_table.REQUEST_ARGUMENTS_FIELD.index = 2
pb_table.REQUEST_ARGUMENTS_FIELD.label = 2
pb_table.REQUEST_ARGUMENTS_FIELD.has_default_value = false
pb_table.REQUEST_ARGUMENTS_FIELD.default_value = ""
pb_table.REQUEST_ARGUMENTS_FIELD.type = 12
pb_table.REQUEST_ARGUMENTS_FIELD.cpp_type = 9

pb_table.REQUEST_OPTIONS_FIELD.name = "options"
pb_table.REQUEST_OPTIONS_FIELD.full_name = ".Request.options"
pb_table.REQUEST_OPTIONS_FIELD.number = 5
pb_table.REQUEST_OPTIONS_FIELD.index = 3
pb_table.REQUEST_OPTIONS_FIELD.label = 1
pb_table.REQUEST_OPTIONS_FIELD.has_default_value = false
pb_table.REQUEST_OPTIONS_FIELD.default_value = 0
pb_table.REQUEST_OPTIONS_FIELD.type = 13
pb_table.REQUEST_OPTIONS_FIELD.cpp_type = 3

REQUEST.name = "Request"
REQUEST.full_name = ".Request"
REQUEST.nested_types = {}
REQUEST.enum_types = {pb_table.REQUEST_OPTION}
REQUEST.fields = {pb_table.REQUEST_SEQUENCE_NUMBER_FIELD, pb_table.REQUEST_METHOD_ID_FIELD, pb_table.REQUEST_ARGUMENTS_FIELD, pb_table.REQUEST_OPTIONS_FIELD}
REQUEST.is_extendable = false
REQUEST.extensions = {}
pb_table.REPLY_STATUS_OK_ENUM.name = "OK"
pb_table.REPLY_STATUS_OK_ENUM.index = 0
pb_table.REPLY_STATUS_OK_ENUM.number = 0
pb_table.REPLY_STATUS_ERROR_ENUM.name = "ERROR"
pb_table.REPLY_STATUS_ERROR_ENUM.index = 1
pb_table.REPLY_STATUS_ERROR_ENUM.number = 1
pb_table.REPLY_STATUS_DUPLICATE_ENUM.name = "DUPLICATE"
pb_table.REPLY_STATUS_DUPLICATE_ENUM.index = 2
pb_table.REPLY_STATUS_DUPLICATE_ENUM.number = 2
pb_table.REPLY_STATUS.name = "Status"
pb_table.REPLY_STATUS.full_name = ".Reply.Status"
pb_table.REPLY_STATUS.values = {pb_table.REPLY_STATUS_OK_ENUM,pb_table.REPLY_STATUS_ERROR_ENUM,pb_table.REPLY_STATUS_DUPLICATE_ENUM}
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.name = "sequence_number"
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.full_name = ".Reply.sequence_number"
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.number = 1
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.index = 0
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.label = 2
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.has_default_value = false
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.default_value = 0
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.type = 13
pb_table.REPLY_SEQUENCE_NUMBER_FIELD.cpp_type = 3

pb_table.REPLY_STATUS_FIELD.name = "status"
pb_table.REPLY_STATUS_FIELD.full_name = ".Reply.status"
pb_table.REPLY_STATUS_FIELD.number = 2
pb_table.REPLY_STATUS_FIELD.index = 1
pb_table.REPLY_STATUS_FIELD.label = 2
pb_table.REPLY_STATUS_FIELD.has_default_value = false
pb_table.REPLY_STATUS_FIELD.default_value = nil
pb_table.REPLY_STATUS_FIELD.enum_type = REPLY_STATUS
pb_table.REPLY_STATUS_FIELD.type = 14
pb_table.REPLY_STATUS_FIELD.cpp_type = 8

pb_table.REPLY_RESULT_FIELD.name = "result"
pb_table.REPLY_RESULT_FIELD.full_name = ".Reply.result"
pb_table.REPLY_RESULT_FIELD.number = 3
pb_table.REPLY_RESULT_FIELD.index = 2
pb_table.REPLY_RESULT_FIELD.label = 1
pb_table.REPLY_RESULT_FIELD.has_default_value = false
pb_table.REPLY_RESULT_FIELD.default_value = ""
pb_table.REPLY_RESULT_FIELD.type = 12
pb_table.REPLY_RESULT_FIELD.cpp_type = 9

REPLY.name = "Reply"
REPLY.full_name = ".Reply"
REPLY.nested_types = {}
REPLY.enum_types = {pb_table.REPLY_STATUS}
REPLY.fields = {pb_table.REPLY_SEQUENCE_NUMBER_FIELD, pb_table.REPLY_STATUS_FIELD, pb_table.REPLY_RESULT_FIELD}
REPLY.is_extendable = false
REPLY.extensions = {}

Reply = protobuf.Message(REPLY)
Request = protobuf.Message(REQUEST)

