-- Generated By protoc-gen-lua Do not Edit
local protobuf = import("net/protobuf/protobuf.lua")


S2SAUTH = protobuf.Descriptor();
local S2SAUTH_TOKEN_FIELD = protobuf.FieldDescriptor();

S2SAUTH_TOKEN_FIELD.name = "token"
S2SAUTH_TOKEN_FIELD.full_name = ".S2SAuth.token"
S2SAUTH_TOKEN_FIELD.number = 1
S2SAUTH_TOKEN_FIELD.index = 0
S2SAUTH_TOKEN_FIELD.label = 2
S2SAUTH_TOKEN_FIELD.has_default_value = false
S2SAUTH_TOKEN_FIELD.default_value = ""
S2SAUTH_TOKEN_FIELD.type = 9
S2SAUTH_TOKEN_FIELD.cpp_type = 9

S2SAUTH.name = "S2SAuth"
S2SAUTH.full_name = ".S2SAuth"
S2SAUTH.nested_types = {}
S2SAUTH.enum_types = {}
S2SAUTH.fields = {S2SAUTH_TOKEN_FIELD}
S2SAUTH.is_extendable = false
S2SAUTH.extensions = {}

S2SAuth = protobuf.Message(S2SAUTH)

