module UI {

    export function setPackageItemExtension() {
        fairygui.UIConfig.defaultScrollDecelerationRate = 0.193;
        fairygui.UIPackage.addPackage(PkgName.common);
        // console.log(PkgName.common);
        fairygui.UIPackage.addPackage(PkgName.bmpfont);
        fairygui.UIPackage.addPackage(PkgName.cards);
        // console.log(PkgName.cards);
        fairygui.UIPackage.addPackage(PkgName.login);
        // console.log(PkgName.login);
        fairygui.UIPackage.addPackage(PkgName.home);
        // console.log(PkgName.home);
        fairygui.UIPackage.addPackage(PkgName.level);
        // console.log(PkgName.level);
        fairygui.UIPackage.addPackage(PkgName.card_b);
        // console.log(PkgName.card_b);
        fairygui.UIPackage.addPackage(PkgName.card_m);
        // console.log(PkgName.card_m);
        fairygui.UIPackage.addPackage(PkgName.card_s);
        // console.log(PkgName.card_s);
	      fairygui.UIPackage.addPackage(PkgName.card_u);
        // console.log(PkgName.card_u);
        fairygui.UIPackage.addPackage(PkgName.cardpool);
        // console.log(PkgName.cardpool);
        fairygui.UIPackage.addPackage(PkgName.battle);
        // console.log(PkgName.battle);
        //fairygui.UIPackage.addPackage(PkgName.campign);
        fairygui.UIPackage.addPackage(PkgName.treasure);
        // console.log(PkgName.treasure);
        fairygui.UIPackage.addPackage(PkgName.pvp);
        // console.log(PkgName.pvp);
        fairygui.UIPackage.addPackage(PkgName.diy);
        // console.log(PkgName.diy);
        fairygui.UIPackage.addPackage(PkgName.guide);
        // console.log(PkgName.guide);
        fairygui.UIPackage.addPackage(PkgName.social);
        // console.log(PkgName.social);
        fairygui.UIPackage.addPackage(PkgName.shop);
        // console.log(PkgName.social);
        fairygui.UIPackage.addPackage(PkgName.reborn);
        fairygui.UIPackage.addPackage(PkgName.equip);
        fairygui.UIPackage.addPackage(PkgName.war);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "tips"), TipsCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "handCardGrid"), HandCardGrid);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpScoreProgressBar"), MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.level, "NewLevelItem"), Level.LevelItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.level, "chapterItem"), Level.ChapterItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.level, "levelTreasure"), Level.ChapterRewardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.level, "appealItem"), Level.LevelHelpItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "resBarBtn"), ResBarBtn);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "resLabel"), ResLabel);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "resList"), ResList);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "rewardResBar"), RewardResBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "castlerSkill"), CastlerSkill);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "cardRareSmall"), CardRareCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "cardRareMiddle"), CardRareCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "smallCard"), CardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "middleCard"), CardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "middleCardBig"), CardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "valueProgressBar"), MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cardpool, "valueProgressBar"), MaskProgressBar);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "cardItem"), BaseCardItem);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "campItem"), Campign.CampItem);
        if (window.gameGlobal.isPC) {
          //  fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "campItem2"), Campign.CampItem);
        }
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "ResItem"), Campign.ResItem);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "proBar"), Campign.CampignProBar);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "proBar2"), Campign.CampignProBar2);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "handCardGrid"), Campign.CampignHandCardGrid);
        //fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.campign, "cardItem"), Campign.ChoiceCardItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "battleGrid"), Battle.GridView);
	      fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "progress"), MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "treasure"), Treasure.TreasureItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "dailyTreasure"), Treasure.DailyTreasureItemCom);
        // fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "treasureAniCom"), Treasure.TreasureAniCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "cardCnt"), Treasure.CardRewardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "goldCnt"), Treasure.GoldRewardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "jadeCnt"), Treasure.JadeRewardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.treasure, "bowlderCnt"), Treasure.BowlderRewardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "starAni"), UI.StarCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner0"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner1"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner2"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner3"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner4"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner5"), UI.BannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBannerMax"), UI.MaxBannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "pvpRankBanner"), UI.PvpRankBannerCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "winNew"), Battle.NewBattleWinCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "loseNew"), Battle.NewBattleLoseCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "emojiChk"), Battle.EmojiTeamChkBtnCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "emojiView1"), Battle.EmojiListViewCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.battle, "emojiView2"), Battle.EmojiListViewCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "cardNumHint"), CardPool.CardNumHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "avatarNumHint"), CardPool.AvatarNumHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "levelNumHint"), Level.LevelNumHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "rankingPlayer"), Pvp.RankPlayerInfoCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "rankingPlayerRankSeason"), Pvp.SeasonRankPlayerInfoCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "videoCard"), Pvp.VideoCardCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "videoDiscuss"), Pvp.VideoDiscussWnd);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "videoDiscussItem"), Pvp.VideoDisItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "worldChat"), Social.WorldChatWndCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "warChat"), Social.WorldChatWndCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "privateChat"), Social.PrivateChatWndCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "friend"), Social.FriendListWndCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "friendItem"), Social.FriendItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "headItemCom"), Social.AvatarItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "privItem"), Social.PrivCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "privCom"), Social.PrivCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "headFrameItemCom"), Social.FrameItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "privateChatNumHint"), Social.PrivateChatHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "applyFriendNumHint"), Social.ApplyFriendHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.common, "socialNewHint"), Social.SocialHintCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.home, "bubbleTips"), Social.InviteBattleHintCom);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "cardCnt"), Shop.CardCntCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "goldCnt"), Shop.GoldCntCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "jadeCnt"), Shop.JadeCntCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "goldItem"), Shop.GoldItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "jadeItem"), Shop.JadeItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "limitGiftItem"), Shop.GiftItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "purchaseItem"), Shop.GiftItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "advipItem"), Shop.GiftVipCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "minivipItem"), Shop.GiftVipCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "treasureItem"), Shop.TreasureItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "freeGold"), Shop.FreeGoldItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "freeJade"), Shop.FreeJadeItemCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "freeTreasure"), Shop.FreeTreasureItemCom);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "gold"), Shop.GoldSellCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "jade"), Shop.JadeSellCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "limitGift"), Shop.GiftSellCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "purchase"), Shop.GiftSellCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "treasure"), Shop.TreasureSellCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.shop, "free"), Shop.FreeSellCom);
        
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "questBtn"), Quest.QuestBtnCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "questItem"), Quest.QuestItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "questTipItem"), Quest.QuestTipItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.level, "levelProgressBar"), MaskProgressBar);
        
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "inviteRewardItem"), Social.InviteRewardItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "inviteHeadItem"), Social.InviteMemberItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.social, "head"), Social.HeadCom);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "rankhandCardGrid"), Pvp.RankHand);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "mailRewardItem"), Pvp.MailInfoItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.pvp, "advertIcon"), WXGame.WXAdvertIconCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.cards, "skinCom"), CardPool.SkinItemCom);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.reborn, "refineCardItem"), Reborn.RefineCardItem);

        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "mainMap"), War.MainMap);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityItem"), War.CityCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "playerItem"), War.WarPlayerItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "emperorApplyItem"), War.EmperorApplyItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "resourceProgressItem"), War.CityInfoBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "progress"), UI.MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "warProgress1"), UI.MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "warProgress2"), UI.MaskProgressBar);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "resourceValueItem"), War.CityInfoCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityDetail"), War.CityDetailCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityBuild"), War.CityBuildCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityAppoint"), War.CityAppointCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "jobItem"), War.CityJobItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "questStatus"), War.CurQuestCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "questItem"), War.WarQuestItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cardHeadItem"), War.WarCardHeadCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "gameoverPanel"), War.WarGameOverPanel);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "warStatusPanel"), War.WarHomeTipPanel);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "fightStatusPanel"), War.WarFightStatusPanel);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityManageFightPanel"), War.CityManageFightCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "campItem"), War.CampIconCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "cityBuildItem"), War.CityBuildItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "noticeFunctionItem"), War.WarNoticeItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "countryAppoint"), War.CountryAppointCom);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "playerChooseItem"), War.PlayerChooseItem);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "shopCard"), War.WarShopWindow);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "shopSkin"), War.WarShopWindow);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "shopEquip"), War.WarShopWindow);
        fairygui.UIObjectFactory.setPackageItemExtension(fairygui.UIPackage.getItemURL(PkgName.war, "shopRes"), War.WarShopWindow);

   }
}