-- Generated By protoc-gen-lua Do not Edit
local protobuf = import("net/protobuf/protobuf.lua")


local SYSTEMID = protobuf.EnumDescriptor();
local SYSTEMID_MISC_ENUM = protobuf.EnumValueDescriptor();

SYSTEMID_MISC_ENUM.name = "MISC"
SYSTEMID_MISC_ENUM.index = 0
SYSTEMID_MISC_ENUM.number = 0
SYSTEMID.name = "SystemID"
SYSTEMID.full_name = ".SystemID"
SYSTEMID.values = {SYSTEMID_MISC_ENUM}

MISC = 0

