-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 长沙友文内购
-- ------------------------------


data = table.protect({
	['roomcards1'] = {
		['price'] = 600,
		['name'] = TEXT('钻石x60'),
		['num'] = 60,
	},
	['roomcards2'] = {
		['price'] = 3000,
		['name'] = TEXT('钻石x300'),
		['num'] = 300,
	},
	['roomcards3'] = {
		['price'] = 9800,
		['name'] = TEXT('钻石x1000'),
		['num'] = 1000,
	},
})
