-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: MM茂名麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_4;round_8;round_12',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('可选'),
		['optionRanking'] = 3,
		['optionType'] = 3,
		['optionMenu'] = 'fengtoupai;kechi;qidui;',
		['defaultMenu'] = 'kechi',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 4,
		['optionType'] = 3,
		['optionMenu'] = 'fenzhurou;keqiangangang',
		['defaultMenu'] = 'fenzhurou',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 5,
		['optionType'] = 3,
		['optionMenu'] = '12zhangluodi;gangbaochengbao;keqianggang',
		['defaultMenu'] = 'gangbaochengbao',
		['isHide'] = 0,
	},
	[6] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 6,
		['optionType'] = 3,
		['optionMenu'] = 'gangshangkaihuax2;qianggangx2;qianggangchengbao',
		['defaultMenu'] = 'gangshangkaihuax2',
		['isHide'] = 0,
	},
	[7] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 7,
		['optionType'] = 1,
		['optionMenu'] = 'fanguipai;baibangui;hongzhonggui;wuguipai',
		['defaultMenu'] = 'wuguipai',
		['isHide'] = 0,
	},
	[8] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 8,
		['optionType'] = 3,
		['optionMenu'] = 'keqiangangang;wuguix2;sidajingang',
		['defaultMenu'] = '',
		['isHide'] = 0,
	},
	[9] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 9,
		['optionType'] = 1,
		['optionMenu'] = 'zimomaima;baozhama;zhuangjiamaima',
		['defaultMenu'] = '',
		['isHide'] = 0,
	},
	[10] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 10,
		['optionType'] = 1,
		['optionMenu'] = 'maima_4;maima_8;maima_12;maima_0;maima_1',
		['defaultMenu'] = 'maima_0',
		['isHide'] = 0,
	},
	[11] = {
		['optionText1'] = TEXT('fanxing'),
		['optionRanking'] = 11,
		['optionType'] = 3,
		['optionMenu'] = 'ddp;qd;hj;hsh;hys;qys;hyj;qyj;zys;xsy;dsy;xsx;dsx;jlbd;ssy;th;dh',
		['defaultMenu'] = '',
		['isHide'] = 0,
	},
})
