-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: YY云阳麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_8;round_16',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'dingque;budingque',
		['defaultMenu'] = 'budingque',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT('可选'),
		['optionRanking'] = 4,
		['optionType'] = 3,
		['optionMenu'] = 'qiansihousi;zhuangsanda;jingoudiao',
		['defaultMenu'] = 'qiansihousi;zhuangsanda;jingoudiao',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 5,
		['optionType'] = 1,
		['optionMenu'] = 'fengding_3;fengding_4;fengding_5',
		['defaultMenu'] = 'fengding_3',
		['isHide'] = 0,
	},
	[6] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 6,
		['optionType'] = 1,
		['optionMenu'] = 'huazhu_5;huazhu_10',
		['defaultMenu'] = 'huazhu_5',
		['isHide'] = 0,
	},
})
