-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: PH平和麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('圈数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'circle_1;circle_2;circle_3;circle_4',
		['defaultMenu'] = 'circle_1',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('金牌'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'sanjinban;sijinban',
		['defaultMenu'] = 'sijinban',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT('可选'),
		['optionRanking'] = 1,
		['optionType'] = 3,
		['optionMenu'] = 'sanjindao_or_sijindao;shuangyou_can_hu',
		['defaultMenu'] = 'sanjindao_or_sijindao',
		['isHide'] = 0,
	},
})
