-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 桃江乐闲内购
-- ------------------------------


data = table.protect({
	['roomcards1'] = {
		['price'] = 600,
		['store_price'] = 1200,
		['name'] = TEXT('钻石x%d'),
		['num'] = 60,
	},
	['roomcards2'] = {
		['price'] = 3000,
		['store_price'] = 6000,
		['name'] = TEXT('钻石x%d'),
		['num'] = 320,
	},
	['roomcards3'] = {
		['price'] = 9800,
		['store_price'] = 19800,
		['name'] = TEXT('钻石x%d'),
		['num'] = 1150,
	},
})
