-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 开新消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['room_card_cost5'] = 12,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 24,
		['room_card_cost3'] = 24,
		['room_card_cost4'] = 24,
		['room_card_cost5'] = 24,
		['aa_round'] = 0,
	},
	[10] = {
		['room_card_cost2'] = 30,
		['room_card_cost3'] = 30,
		['room_card_cost4'] = 30,
		['room_card_cost5'] = 30,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 36,
		['room_card_cost3'] = 36,
		['room_card_cost4'] = 36,
		['room_card_cost5'] = 36,
		['aa_round'] = 0,
	},
	[20] = {
		['room_card_cost2'] = 60,
		['room_card_cost3'] = 60,
		['room_card_cost4'] = 60,
		['room_card_cost5'] = 60,
		['aa_round'] = 0,
	},
	[24] = {
		['room_card_cost2'] = 72,
		['room_card_cost3'] = 72,
		['room_card_cost4'] = 72,
		['room_card_cost5'] = 72,
		['aa_round'] = 0,
	},
})
