-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 长沙友文消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost'] = 12,
	},
	[8] = {
		['room_card_cost'] = 24,
	},
	[12] = {
		['room_card_cost'] = 36,
	},
})
