-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 卡五星消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['aa_round'] = 0,
	},
	[16] = {
		['room_card_cost2'] = 16,
		['room_card_cost3'] = 16,
		['room_card_cost4'] = 16,
		['aa_round'] = 0,
	},
})
