-- ------------------------------
-- desc: generated by xls2data.py
-- source: poker_rules.xlsx
-- sheet: 天九王消耗
-- ------------------------------


data = table.protect({
	[1] = {
		['room_card_cost2'] = 6,
		['room_card_cost3'] = 6,
		['room_card_cost4'] = 6,
		['room_card_cost5'] = 6,
		['aa_round'] = 0,
	},
	[4] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[10] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[16] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['room_card_cost5'] = 8,
		['aa_round'] = 0,
	},
	[20] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['room_card_cost5'] = 8,
		['aa_round'] = 0,
	},
	[24] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['room_card_cost5'] = 8,
		['aa_round'] = 0,
	},
})
