-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 平和红包
-- ------------------------------


data = table.protect({
	['1'] = {
		['amount_min'] = 100,
		['amount_max'] = 150,
		['pro'] = 100,
	},
})
