-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 初始资源数量
-- ------------------------------


data = table.protect({
	['tj_lexian'] = {
		['room_card_count'] = 24,
		['gold_coin_count'] = 1000,
	},
	['openew'] = {
		['room_card_count'] = 120,
		['gold_coin_count'] = 1000,
	},
	['ds_queyue'] = {
		['room_card_count'] = 20,
		['gold_coin_count'] = 1000,
	},
	['test'] = {
		['room_card_count'] = 24,
		['gold_coin_count'] = 1000,
	},
	['ly_youwen'] = {
		['room_card_count'] = 120,
		['gold_coin_count'] = 1000,
	},
	['yy_doudou'] = {
		['room_card_count'] = 24,
		['gold_coin_count'] = 1000,
	},
	['rc_xianle'] = {
		['room_card_count'] = 32,
		['gold_coin_count'] = 1000,
	},
	['xy_hanshui'] = {
		['room_card_count'] = 120,
		['gold_coin_count'] = 1000,
	},
	['jz_laiba'] = {
		['room_card_count'] = 12,
		['gold_coin_count'] = 1000,
	},
	['nc_tianjiuwang'] = {
		['room_card_count'] = 20,
		['gold_coin_count'] = 1000,
	},
	['za_queyue'] = {
		['room_card_count'] = 20,
		['gold_coin_count'] = 1000,
	},
	['qs_pinghe'] = {
		['room_card_count'] = 24,
		['gold_coin_count'] = 1000,
	},
})
