-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: RC荣城麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_4;round_8;round_16',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 3,
		['optionMenu'] = 'kechi;daifengpai;erwubazhang;piaofen',
		['defaultMenu'] = 'kechi;daifengpai;erwubazhang',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 4,
		['optionType'] = 3,
		['optionMenu'] = 'qiluo;minglou;shuaiquan',
		['defaultMenu'] = 'qiluo;minglou;shuaiquan',
		['isHide'] = 0,
	},
})
