-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 工作表2
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'circle_1;circle_2;circle_3',
		['defaultMenu'] = 'circle_1',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_3',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 3,
		['optionMenu'] = 'genzhuang;sankoubaohu',
		['defaultMenu'] = 'genzhuang;sankoubaohu',
		['isHide'] = 0,
	},
})
