-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: DD倒倒胡
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_4;round_8;round_12',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'jiepao;zimo',
		['defaultMenu'] = 'jiepao',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 4,
		['optionType'] = 1,
		['optionMenu'] = '1tuo1;1tuo2;2tuo3;3tuo5',
		['defaultMenu'] = '1tuo2',
		['isHide'] = 0,
	},
})
