-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: HZ红中麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_4;round_8;round_12',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('可选'),
		['optionRanking'] = 3,
		['optionType'] = 3,
		['optionMenu'] = 'hostmode;piaofen',
		['defaultMenu'] = 'hostmode',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 4,
		['optionType'] = 1,
		['optionMenu'] = '159zhuaniao;jinniao;feiniao',
		['defaultMenu'] = 'jinniao',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT('zhuaniao'),
		['optionRanking'] = 5,
		['optionType'] = 1,
		['optionMenu'] = 'bird_2;bird_4;bird_6;bird_0;bird_1',
		['defaultMenu'] = 'bird_2',
		['isHide'] = 0,
	},
})
