-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 白河卡五星
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_8;round_16',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_3;player_2',
		['defaultMenu'] = 'player_3',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'quanpindao;banpindao',
		['defaultMenu'] = 'quanpindao',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 4,
		['optionType'] = 3,
		['optionMenu'] = 'fengding_8',
		['defaultMenu'] = 'fengding_8',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 5,
		['optionType'] = 1,
		['optionMenu'] = 'liangdaozimomaima;xy_zimomaima',
		['defaultMenu'] = 'liangdaozimomaima',
		['isHide'] = 0,
	},
	[6] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 6,
		['optionType'] = 1,
		['optionMenu'] = 'maima_1;maima_6;maima_0',
		['defaultMenu'] = 'maima_1',
		['isHide'] = 0,
	},
})
