-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: TJ蓟州麻将
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'circle_1;circle_2;circle_3',
		['defaultMenu'] = 'circle_1',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_4',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('可选'),
		['optionRanking'] = 3,
		['optionType'] = 3,
		['optionMenu'] = 'qidui;jingang;chan;koupaimode',
		['defaultMenu'] = 'qidui;jingang',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 4,
		['optionType'] = 3,
		['optionMenu'] = 'la;chuai',
		['defaultMenu'] = '',
		['isHide'] = 0,
	},
})
