-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 诏安消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost2'] = 2,
		['room_card_cost3'] = 3,
		['room_card_cost4'] = 4,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 6,
		['room_card_cost4'] = 8,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 6,
		['room_card_cost3'] = 9,
		['room_card_cost4'] = 12,
		['aa_round'] = 0,
	},
})
