-- ------------------------------
-- desc: generated by xls2data.py
-- source: club_config.xlsx
-- sheet: 省份
-- ------------------------------


data = table.protect({
	[1] = {
		['code'] = 101,
		['name'] = TEXT('北京'),
	},
	[2] = {
		['code'] = 102,
		['name'] = TEXT('天津'),
	},
	[3] = {
		['code'] = 103,
		['name'] = TEXT('河北'),
	},
	[4] = {
		['code'] = 104,
		['name'] = TEXT('山西'),
	},
	[5] = {
		['code'] = 105,
		['name'] = TEXT('内蒙古'),
	},
	[6] = {
		['code'] = 106,
		['name'] = TEXT('辽宁'),
	},
	[7] = {
		['code'] = 107,
		['name'] = TEXT('吉林'),
	},
	[8] = {
		['code'] = 108,
		['name'] = TEXT('黑龙江'),
	},
	[9] = {
		['code'] = 109,
		['name'] = TEXT('上海'),
	},
	[10] = {
		['code'] = 110,
		['name'] = TEXT('江苏'),
	},
	[11] = {
		['code'] = 111,
		['name'] = TEXT('浙江'),
	},
	[12] = {
		['code'] = 112,
		['name'] = TEXT('安徽'),
	},
	[13] = {
		['code'] = 113,
		['name'] = TEXT('福建'),
	},
	[14] = {
		['code'] = 114,
		['name'] = TEXT('江西'),
	},
	[15] = {
		['code'] = 115,
		['name'] = TEXT('山东'),
	},
	[16] = {
		['code'] = 116,
		['name'] = TEXT('河南'),
	},
	[17] = {
		['code'] = 117,
		['name'] = TEXT('湖北'),
	},
	[18] = {
		['code'] = 118,
		['name'] = TEXT('湖南'),
	},
	[19] = {
		['code'] = 119,
		['name'] = TEXT('广东'),
	},
	[20] = {
		['code'] = 120,
		['name'] = TEXT('广西'),
	},
	[21] = {
		['code'] = 121,
		['name'] = TEXT('海南'),
	},
	[22] = {
		['code'] = 122,
		['name'] = TEXT('重庆'),
	},
	[23] = {
		['code'] = 123,
		['name'] = TEXT('四川'),
	},
	[24] = {
		['code'] = 124,
		['name'] = TEXT('贵州'),
	},
	[25] = {
		['code'] = 125,
		['name'] = TEXT('云南'),
	},
	[26] = {
		['code'] = 126,
		['name'] = TEXT('西藏'),
	},
	[27] = {
		['code'] = 127,
		['name'] = TEXT('陕西'),
	},
	[28] = {
		['code'] = 128,
		['name'] = TEXT('甘肃'),
	},
	[29] = {
		['code'] = 129,
		['name'] = TEXT('青海'),
	},
	[30] = {
		['code'] = 130,
		['name'] = TEXT('宁夏'),
	},
	[31] = {
		['code'] = 131,
		['name'] = TEXT('新疆'),
	},
	[32] = {
		['code'] = 132,
		['name'] = TEXT('台湾'),
	},
	[33] = {
		['code'] = 133,
		['name'] = TEXT('香港'),
	},
	[34] = {
		['code'] = 134,
		['name'] = TEXT('澳门'),
	},
})
