-- ------------------------------
-- desc: generated by xls2data.py
-- source: channel.xlsx
-- sheet: 语音路径
-- ------------------------------


data = table.protect({
	['niuniu'] = {
		['name'] = '牛牛',
		['fanyanPath'] = 'niuniu/',
		['fanyanData'] = 'data/info/info_voices_nctjw_niuniu.lua',
	},
	['paijiu'] = {
		['name'] = '牌九',
		['fanyanPath'] = 'paijiu/',
		['fanyanData'] = 'data/info/info_voices_nctjw_paijiu.lua',
	},
})
