-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 友文消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost2'] = 2,
		['room_card_cost3'] = 2,
		['room_card_cost4'] = 2,
		['room_card_cost5'] = 2,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[10] = {
		['room_card_cost2'] = 6,
		['room_card_cost3'] = 6,
		['room_card_cost4'] = 6,
		['room_card_cost5'] = 6,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 6,
		['room_card_cost3'] = 6,
		['room_card_cost4'] = 6,
		['room_card_cost5'] = 6,
		['aa_round'] = 0,
	},
	[20] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['room_card_cost5'] = 12,
		['aa_round'] = 0,
	},
})
