-- ------------------------------
-- desc: generated by xls2data.py
-- source: group_config.xlsx
-- sheet: 俱乐部渠道配置
-- ------------------------------


data = table.protect({
	['test'] = {
		['max_group_count'] = 3,
		['room_card_cost'] = 1,
		['max_member_count'] = 500,
	},
	['za_queyue'] = {
		['max_group_count'] = 3,
		['room_card_cost'] = 5000,
		['max_member_count'] = 500,
	},
})
