-- ------------------------------
-- desc: generated by xls2data.py
-- source: group_config.xlsx
-- sheet: 俱乐部消息
-- ------------------------------


data = table.protect({
	[1] = {
		['template'] = '#co{nickname}({user_id})#n请求加入群<#co{group_name}({group_id})#n>，并留言：{left_words}。',
	},
	[2] = {
		['template'] = '群<#co{group_name}({group_id})#n>管理员#cg通过了#n您的申请。',
	},
	[3] = {
		['template'] = '群<#co{group_name}({group_id})#n>管理员#cr拒绝了#n您的申请#n。',
	},
	[8] = {
		['template'] = '#co{nickname}({user_id})#n#cr离开了#n群<#co{group_name}({group_id})#n>。',
	},
	[9] = {
		['template'] = '群<#co{group_name}({group_id})#n>已经解散。',
	},
	[10] = {
		['template'] = '群<#co{group_name}({group_id})#n>管理员将您#cr踢出了#n群。',
	},
})
