-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: text
-- ------------------------------


data = table.protect({
	[1] = {
		['cn'] = '%d秒',
		['tw'] = '％d秒',
		['en'] = '％dsecond',
	},
	[2] = {
		['cn'] = '密码',
		['tw'] = '密碼',
		['en'] = 'Password',
	},
	[3] = {
		['cn'] = '分数',
		['tw'] = '分數',
		['en'] = 'Score',
	},
	[4] = {
		['cn'] = '占领',
		['tw'] = '佔領',
		['en'] = 'Capture',
	},
	[5] = {
		['cn'] = '执行',
		['tw'] = '執行',
		['en'] = 'Execute',
	},
	[6] = {
		['cn'] = '匹配',
		['tw'] = '匹配',
		['en'] = 'Match',
	},
	[7] = {
		['cn'] = '投降',
		['tw'] = '投降',
		['en'] = 'Surrender',
	},
	[8] = {
		['cn'] = '队伍',
		['tw'] = '隊伍',
		['en'] = 'Group',
	},
	[9] = {
		['cn'] = '生存',
		['tw'] = '生存',
		['en'] = 'Survival',
	},
	[10] = {
		['cn'] = '乱斗',
		['tw'] = '亂鬥',
		['en'] = 'Melee',
	},
	[11] = {
		['cn'] = '确定',
		['tw'] = '確定',
		['en'] = 'Yes',
	},
	[12] = {
		['cn'] = '兵数',
		['tw'] = '兵數',
		['en'] = 'Army',
	},
	[13] = {
		['cn'] = '技能',
		['tw'] = '技能',
		['en'] = 'Skill',
	},
	[14] = {
		['cn'] = '胜利',
		['tw'] = '勝利',
		['en'] = 'Victory',
	},
	[15] = {
		['cn'] = '更新',
		['tw'] = '更新',
		['en'] = 'Update',
	},
	[16] = {
		['cn'] = '邮箱',
		['tw'] = '郵箱',
		['en'] = 'Email',
	},
	[17] = {
		['cn'] = '房间',
		['tw'] = '房間',
		['en'] = 'Room',
	},
	[18] = {
		['cn'] = '玩家',
		['tw'] = '玩家',
		['en'] = 'Player',
	},
	[19] = {
		['cn'] = '提示',
		['tw'] = '提示',
		['en'] = 'Tip',
	},
	[20] = {
		['cn'] = '进攻',
		['tw'] = '進攻',
		['en'] = 'Attack',
	},
	[21] = {
		['cn'] = '#c613701消耗：#n#c03670d%d#n',
		['tw'] = '#c613701消耗：#n#c03670d%d#n',
		['en'] = '#c613701Consumption: #n#c03670d%d#n',
	},
	[22] = {
		['cn'] = '%03d服',
		['tw'] = '%03d服',
		['en'] = '%03dserver',
	},
	[23] = {
		['cn'] = '胜利！',
		['tw'] = '勝利！',
		['en'] = 'Victory！',
	},
	[24] = {
		['cn'] = '用户名',
		['tw'] = '用戶名',
		['en'] = 'User name',
	},
	[25] = {
		['cn'] = '兵球数',
		['tw'] = '兵球數',
		['en'] = 'Soldier Ball',
	},
	[26] = {
		['cn'] = '母球数',
		['tw'] = '母球數',
		['en'] = 'Mother Ball',
	},
	[27] = {
		['cn'] = '技能点',
		['tw'] = '技能點',
		['en'] = 'Skill Point',
	},
	[28] = {
		['cn'] = '升级中...',
		['tw'] = '陞級中…',
		['en'] = 'Upgrading...',
	},
	[29] = {
		['cn'] = '通讯中...',
		['tw'] = '通訊中…',
		['en'] = 'Communicating...',
	},
	[30] = {
		['cn'] = '确认密码',
		['tw'] = '確認密碼',
		['en'] = 'Confirm Password',
	},
	[31] = {
		['cn'] = '中立母球',
		['tw'] = '中立母球',
		['en'] = 'Neutral Mother Ball',
	},
	[32] = {
		['cn'] = '移入技能槽',
		['tw'] = '移入技能槽',
		['en'] = 'Add',
	},
	[33] = {
		['cn'] = '移出技能槽',
		['tw'] = '移出技能槽',
		['en'] = 'Remove',
	},
	[34] = {
		['cn'] = '投降',
		['tw'] = '投降',
		['en'] = 'Surrender',
	},
	[35] = {
		['cn'] = '团战模式',
		['tw'] = '隊伍模式',
		['en'] = 'Group Mode',
	},
	[36] = {
		['cn'] = '生存模式',
		['tw'] = '生存模式',
		['en'] = 'Survival Mode',
	},
	[37] = {
		['cn'] = '乱斗模式',
		['tw'] = '亂鬥模式',
		['en'] = 'Melee Mode',
	},
	[38] = {
		['cn'] = '操作指引',
		['tw'] = '操作指引',
		['en'] = 'Operational Guidance',
	},
	[39] = {
		['cn'] = '继续',
		['tw'] = '繼續',
		['en'] = 'Continue',
	},
	[40] = {
		['cn'] = '启动出错',
		['tw'] = '啟動出錯',
		['en'] = 'Initialization Error',
	},
	[41] = {
		['cn'] = '绑定成功',
		['tw'] = '綁定成功',
		['en'] = 'Binding successful',
	},
	[42] = {
		['cn'] = '登录失败',
		['tw'] = '登入失敗',
		['en'] = 'Logging-in Failure',
	},
	[43] = {
		['cn'] = '绑定失败',
		['tw'] = '綁定失敗',
		['en'] = 'Binding Failure',
	},
	[44] = {
		['cn'] = '操作失败',
		['tw'] = '操作失敗',
		['en'] = 'Operation Failure',
	},
	[45] = {
		['cn'] = '通讯失败',
		['tw'] = '通訊失敗',
		['en'] = 'Communication Failure',
	},
	[46] = {
		['cn'] = '升级作用',
		['tw'] = '陞級作用',
		['en'] = 'Upgrade Bonus',
	},
	[47] = {
		['cn'] = '网络错误',
		['tw'] = '網絡錯誤',
		['en'] = 'Network Error',
	},
	[48] = {
		['cn'] = '彩虹币不足',
		['tw'] = '彩虹幣不足',
		['en'] = 'Insufficient Rainbow Currency',
	},
	[49] = {
		['cn'] = '注册',
		['tw'] = '注册',
		['en'] = 'Register',
	},
	[50] = {
		['cn'] = '请求超时',
		['tw'] = '請求超時',
		['en'] = 'Request Timeout',
	},
	[51] = {
		['cn'] = '温馨提示',
		['tw'] = '溫馨提示',
		['en'] = 'Tips',
	},
	[52] = {
		['cn'] = '选择地图',
		['tw'] = '選擇地圖',
		['en'] = 'Select Map',
	},
	[53] = {
		['cn'] = '准备开战！',
		['tw'] = '準備開戰！',
		['en'] = 'Ready to Start！',
	},
	[54] = {
		['cn'] = '服务器 %03d',
		['tw'] = '伺服器 %03d',
		['en'] = 'Server %03d',
	},
	[55] = {
		['cn'] = '%03d -- %03d服',
		['tw'] = '%03d -- %03d服',
		['en'] = '%03d -- %03dserver',
	},
	[56] = {
		['cn'] = '细胞大作战',
		['tw'] = '細胞大作戰',
		['en'] = 'cell.io',
	},
	[57] = {
		['cn'] = '兵球数量：',
		['tw'] = '兵球數量：',
		['en'] = 'Soldier Ball: ',
	},
	[58] = {
		['cn'] = '母球等级：',
		['tw'] = '母球等級：',
		['en'] = 'Mother Ball: ',
	},
	[59] = {
		['cn'] = '你确定要投降吗？',
		['tw'] = '你確定要投降嗎？',
		['en'] = 'Are you sure to surrender?',
	},
	[60] = {
		['cn'] = '订单已提交',
		['tw'] = '訂單已提交',
		['en'] = 'Order has been submitted',
	},
	[61] = {
		['cn'] = '找不到玩家',
		['tw'] = '找不到玩家',
		['en'] = 'Cannot find any player',
	},
	[62] = {
		['cn'] = '技能冷却中',
		['tw'] = '技能冷卻中',
		['en'] = 'Skill is cooling down',
	},
	[63] = {
		['cn'] = '技能点数不足',
		['tw'] = '技能點數不足',
		['en'] = 'Insufficient skill point',
	},
	[64] = {
		['cn'] = '%s已经投降了',
		['tw'] = '%s已經投降了',
		['en'] = '%s has surrendered',
	},
	[65] = {
		['cn'] = '技能2级开放',
		['tw'] = '技能2級開放',
		['en'] = 'Skill to be unlocked in level 2',
	},
	[66] = {
		['cn'] = '点击输入密码',
		['tw'] = '點擊輸入密碼',
		['en'] = 'Click to enter password',
	},
	[67] = {
		['cn'] = '不可用的目标',
		['tw'] = '不可用的目標',
		['en'] = 'Target unavailable',
	},
	[68] = {
		['cn'] = '点击开始体验',
		['tw'] = '點擊開始',
		['en'] = 'Click to Start',
	},
	[69] = {
		['cn'] = '请输入用户名',
		['tw'] = '請輸入用戶名',
		['en'] = 'Enter User Name',
	},
	[70] = {
		['cn'] = '命令执行成功',
		['tw'] = '命令執行成功',
		['en'] = 'Command has been executed ',
	},
	[71] = {
		['cn'] = '正在登录游戏',
		['tw'] = '正在登入遊戲',
		['en'] = 'Logging-in…',
	},
	[72] = {
		['cn'] = '用户注册成功',
		['tw'] = '用戶註冊成功',
		['en'] = 'Successfully registered ',
	},
	[73] = {
		['cn'] = '密码修改成功',
		['tw'] = '密碼修改成功',
		['en'] = 'Password has been modified ',
	},
	[74] = {
		['cn'] = '没有这个命令',
		['tw'] = '沒有這個命令',
		['en'] = 'The command is not found',
	},
	[75] = {
		['cn'] = '账号已被占用',
		['tw'] = '帳號已被佔用',
		['en'] = 'Account Already Existed',
	},
	[76] = {
		['cn'] = '命令参数错误',
		['tw'] = '命令參數錯誤',
		['en'] = 'Command Parameter Error',
	},
	[77] = {
		['cn'] = '游戏资源更新',
		['tw'] = '遊戲資源更新',
		['en'] = 'Game Resource Update',
	},
	[78] = {
		['cn'] = '技能点数不足',
		['tw'] = '技能點數不足',
		['en'] = 'Insufficient Skill Point',
	},
	[79] = {
		['cn'] = '正在搜索玩家',
		['tw'] = '正在蒐索玩家',
		['en'] = 'Searching for Player',
	},
	[80] = {
		['cn'] = '超出上限条件',
		['tw'] = '超出上限條件',
		['en'] = 'Beyond Upper Limit',
	},
	[81] = {
		['cn'] = '正在检查配置',
		['tw'] = '正在檢查配寘',
		['en'] = 'Checking Configuration',
	},
	[82] = {
		['cn'] = '点击输入账号',
		['tw'] = '點擊輸入帳號',
		['en'] = 'Click to Enter Account',
	},
	[83] = {
		['cn'] = '正在检查配置',
		['tw'] = '正在檢查配寘',
		['en'] = 'Checking Configuration',
	},
	[84] = {
		['cn'] = '账号不能为空',
		['tw'] = '帳號不能為空',
		['en'] = 'Valid account is required',
	},
	[85] = {
		['cn'] = '暂未开放',
		['tw'] = '暫未開放',
		['en'] = 'Coming soon…',
	},
	[86] = {
		['cn'] = '黑球：+%d',
		['tw'] = '黑球：+%d',
		['en'] = 'Black Ball: +%d',
	},
	[87] = {
		['cn'] = '母球等级：Lv%d',
		['tw'] = '母球等級：Lv%d',
		['en'] = 'Mother Ball: Lv%d',
	},
	[88] = {
		['cn'] = '兵球数量：%d/%d',
		['tw'] = '兵球數量：%d/%d',
		['en'] = 'Soldier Ball: %d/%d',
	},
	[89] = {
		['cn'] = '%s已经被消灭了',
		['tw'] = '%s已經被消滅了',
		['en'] = '%s is defeat',
	},
	[90] = {
		['cn'] = '检测资源更新...',
		['tw'] = '檢測資源更新…',
		['en'] = 'Resource updating...',
	},
	[91] = {
		['cn'] = '兵球数量：%d/%d',
		['tw'] = '兵球數量：%d/%d',
		['en'] = 'Soldier Ball: %d/%d',
	},
	[92] = {
		['cn'] = '服务器 %03d - %03d',
		['tw'] = '伺服器%03d -- %03d',
		['en'] = 'server%03d - %03d',
	},
	[93] = {
		['cn'] = '没有可用的目标',
		['tw'] = '沒有可用的目標',
		['en'] = 'No target available',
	},
	[94] = {
		['cn'] = '错误的目标类型',
		['tw'] = '錯誤的目標類型',
		['en'] = 'Wrong target type',
	},
	[95] = {
		['cn'] = '技能池还没初始化',
		['tw'] = '技能池還沒初始化',
		['en'] = 'Skill is not initialized',
	},
	[96] = {
		['cn'] = '服务器验证失败',
		['tw'] = '服務器驗證失敗',
		['en'] = 'Server Verification Failure',
	},
	[97] = {
		['cn'] = '连接服务器失败',
		['tw'] = '連接服務器失敗',
		['en'] = 'Unable to connect to server',
	},
	[98] = {
		['cn'] = '初始化信息失败',
		['tw'] = '初始化資訊失敗',
		['en'] = 'Unable to initialize information',
	},
	[99] = {
		['cn'] = '正在连接服务器',
		['tw'] = '正在連接服務器',
		['en'] = 'Connecting to Server',
	},
	[100] = {
		['cn'] = '最近登录服务器',
		['tw'] = '最近登入服務器',
		['en'] = 'Server logged-in recently',
	},
	[101] = {
		['cn'] = '无法解锁该技能',
		['tw'] = '無法解鎖該技能',
		['en'] = 'Unable to Unlock Skill',
	},
	[102] = {
		['cn'] = '请求错误，CODE: %d',
		['tw'] = '請求錯誤，CODE: %d',
		['en'] = 'Request Error,%d CODE: ',
	},
	[103] = {
		['cn'] = '重新连接服务器...',
		['tw'] = '重新連接服務器…',
		['en'] = 'Reconnecting to Server…',
	},
	[104] = {
		['cn'] = '再次确认密码',
		['tw'] = '再次輸入密碼',
		['en'] = 'Confirm Password',
	},
	[105] = {
		['cn'] = '点击进入游戏',
		['tw'] = '點擊進入遊戲',
		['en'] = 'Click to Enter the Game',
	},
	[106] = {
		['cn'] = '用于找回密码(可选)',
		['tw'] = '用於找回密碼（可選）',
		['en'] = 'For Retrieving Password (optional)',
	},
	[107] = {
		['cn'] = '【单击】#c2b3501占领',
		['tw'] = '【按一下】#c2b3501佔領',
		['en'] = '[Click] #c2b3501 Occupation',
	},
	[108] = {
		['cn'] = '【拖动】#c2b3501取消',
		['tw'] = '【拖動】#c2b3501取消',
		['en'] = '[Drag]#c2b3501 Cancel',
	},
	[109] = {
		['cn'] = '【单击】#c2b3501升级',
		['tw'] = '【按一下】#c2b3501陞級',
		['en'] = '[Click] #c2b3501 Upgrade',
	},
	[110] = {
		['cn'] = '【拖动】#c2b3501派兵',
		['tw'] = '【拖動】#c2b3501派兵',
		['en'] = '[Drag]#c2b3501Dispatch',
	},
	[111] = {
		['cn'] = '正在重新加入战斗...',
		['tw'] = '正在重新加入戰鬥…',
		['en'] = 'Rejoin the battle…',
	},
	[112] = {
		['cn'] = '点击开始（%ds）',
		['tw'] = '點擊開始（%ds）',
		['en'] = 'Click to start（%ds）',
	},
	[113] = {
		['cn'] = '正在注销账号，请稍候',
		['tw'] = '正在註銷帳號，請稍候',
		['en'] = 'Logging out your account, please wait',
	},
	[114] = {
		['cn'] = '正在切换账号，请稍候',
		['tw'] = '正在切換帳號，請稍候',
		['en'] = 'Switching to another account, please wait',
	},
	[115] = {
		['cn'] = '本局游戏还剩#cr1#n分钟！',
		['tw'] = '本局遊戲還剩#cr1#n分鐘！',
		['en'] = ' #cr1#n minutes left！',
	},
	[116] = {
		['cn'] = '目标不满足技能施放条件',
		['tw'] = '目標不滿足技能施放條件',
		['en'] = 'Invalid Target.',
	},
	[117] = {
		['cn'] = '您已出局，不能施放技能',
		['tw'] = '您已出局，不能施放技能',
		['en'] = 'You are out and cannot use skills.',
	},
	[118] = {
		['cn'] = '注册',
		['tw'] = '注册',
		['en'] = 'Register',
	},
	[119] = {
		['cn'] = '检测更新失败，请检查网络',
		['tw'] = '檢測更新失敗，請檢查網絡',
		['en'] = 'Update failure, please check the network.',
	},
	[120] = {
		['cn'] = '我是中立玩家，不能施放技能',
		['tw'] = '我是中立玩家，不能施放技能',
		['en'] = 'I am a neutral player and cannot use skills',
	},
	[121] = {
		['cn'] = '游戏有内容更新，请重启游戏',
		['tw'] = '遊戲有內容更新，請重啓遊戲',
		['en'] = 'Software updated, please restart the game.',
	},
	[122] = {
		['cn'] = '还缺少#cfb1515%d#n个兵球可以升级',
		['tw'] = '還缺少#cfb1515%d#n個兵球可以陞級',
		['en'] = 'You need #cfb1515%d#n soldier balls more.',
	},
	[123] = {
		['cn'] = '游戏已有更新，请下载最新版本',
		['tw'] = '遊戲有內容更新，请下载最新版本',
		['en'] = 'New version is released, please download the latest version.',
	},
	[124] = {
		['cn'] = '游戏已有更新，请更新最新版本',
		['tw'] = '遊戲有內容更新，請重啓遊戲',
		['en'] = 'New version is released, please restart the game to update.',
	},
	[125] = {
		['cn'] = '1.提高产兵速度\n2.提高兵力上限\n3.获得技能点数',
		['tw'] = '1.提高兵球生產速度\n2.提高兵球數量上限\n3.獲得技能點數',
		['en'] = '1.Raise growth rate of soldiers\n2.Raise max number of soldiers\n3.Gain skill points',
	},
	[126] = {
		['cn'] = '您的网络状态不稳定，网络连接已断开，请尝试重新连接',
		['tw'] = '您的網絡狀態不穩定，網絡連接已斷開，請嘗試重新連接',
		['en'] = 'Your network is not stable, the network is disconnected. Please try again.',
	},
	[127] = {
		['cn'] = '请耐心等待，还有一点资源需要更新',
		['tw'] = '請耐心等待，還有一點資源需要更新',
		['en'] = 'Be patient, the updating will be compleleted soon',
	},
	[128] = {
		['cn'] = '发现有%s的游戏资源需要更新，确定要下载吗？',
		['tw'] = '發現有%s的遊戲資源需要更新，確定要下載嗎？',
		['en'] = 'There is %s game resources to be updated. Are you sure you want to download it?',
	},
	[129] = {
		['cn'] = '发现有%s的游戏资源需要更新，当前已连接WIFI，请放心下载吧！',
		['tw'] = '發現有%s的遊戲資源需要更新，當前已連接WIFI，請放心下載吧！',
		['en'] = 'There is %s game resources to be updated. You have been connected to WIFI. Download it for free!',
	},
	[130] = {
		['cn'] = '出战技能',
		['tw'] = '出戰技能',
		['en'] = 'Using Skill',
	},
	[131] = {
		['cn'] = '登陆',
		['tw'] = '登入',
		['en'] = 'Login',
	},
	[132] = {
		['cn'] = '发送',
		['tw'] = '發送',
		['en'] = 'Send',
	},
	[133] = {
		['cn'] = '语言选择',
		['tw'] = '語言選擇',
		['en'] = 'Language',
	},
	[134] = {
		['cn'] = '秒',
		['tw'] = '秒',
		['en'] = 'second',
	},
	[135] = {
		['cn'] = '天',
		['tw'] = '天',
		['en'] = 'day',
	},
	[136] = {
		['cn'] = '%d分',
		['tw'] = '%d分',
		['en'] = '%dminutes',
	},
	[137] = {
		['cn'] = '分钟',
		['tw'] = '分鐘',
		['en'] = 'minute',
	},
	[138] = {
		['cn'] = '小时',
		['tw'] = '小時',
		['en'] = 'hour',
	},
	[139] = {
		['cn'] = '%d天%s',
		['tw'] = '%d天%s',
		['en'] = '%ddays%s',
	},
	[140] = {
		['cn'] = '%.1f万',
		['tw'] = '%.1f萬',
		['en'] = '%.1f0000',
	},
	[141] = {
		['cn'] = '%d小时',
		['tw'] = '%d小時',
		['en'] = '%dhours',
	},
	[142] = {
		['cn'] = '%d分%d秒',
		['tw'] = '%d分%d秒',
		['en'] = '%dminutes%dseconds',
	},
	[143] = {
		['cn'] = '%d天%d时',
		['tw'] = '%d天%d時',
		['en'] = '%dday%dhours',
	},
	[144] = {
		['cn'] = '%d小时%d分',
		['tw'] = '%d小時%d分',
		['en'] = '%dhours%dminutes',
	},
	[145] = {
		['cn'] = '%d分钟%d秒',
		['tw'] = '%d分鐘%d秒',
		['en'] = '%dminutes%dseconds',
	},
	[146] = {
		['cn'] = '%d天%d小时',
		['tw'] = '%d天%d小時',
		['en'] = '%ddays%dhours',
	},
	[147] = {
		['cn'] = '%d小时%d分钟',
		['tw'] = '%d小時%d分鐘',
		['en'] = '%dhours%dminutes',
	},
	[148] = {
		['cn'] = '%d小时%d分%d秒',
		['tw'] = '%d小時%d分%d秒',
		['en'] = '%dhours%dminutes%dseconds',
	},
	[149] = {
		['cn'] = '游戏维护中，将持续%s至%s。时间可能延长，给您带来不便，请谅解。',
		['tw'] = '遊戲維護中，將持續%s至%s。時間可能延長，給您帶來不便，請諒解。',
		['en'] = 'Game maintaining. It will last for %s to %s or more. Sorry for the inconvenience.',
	},
	[150] = {
		['cn'] = '三天前',
		['tw'] = '三天前',
		['en'] = 'Three days ago',
	},
	[151] = {
		['cn'] = '三天后',
		['tw'] = '三天后',
		['en'] = 'Three days later',
	},
	[152] = {
		['cn'] = '今天 %02d:%02d',
		['tw'] = '今天 %02d:%02d',
		['en'] = 'Today %02d: %02d',
	},
	[153] = {
		['cn'] = '后天 %02d:%02d',
		['tw'] = '後天 %02d:%02d',
		['en'] = 'The day after tomorrow %02d: %02d',
	},
	[154] = {
		['cn'] = '明天 %02d:%02d',
		['tw'] = '明天 %02d:%02d',
		['en'] = 'Tomorrow %02d: %02d',
	},
	[155] = {
		['cn'] = '昨天 %02d:%02d',
		['tw'] = '昨天 %02d:%02d',
		['en'] = 'Yesterday %02d: %02d',
	},
	[156] = {
		['cn'] = '很久很久以前',
		['tw'] = '很久很久以前',
		['en'] = 'Long long time ago',
	},
	[157] = {
		['cn'] = '两天前 %02d:%02d',
		['tw'] = '兩天前 %02d:%02d',
		['en'] = 'Two days ago %02d: %02d',
	},
	[158] = {
		['cn'] = '%d月%d日%.2d:%.2d',
		['tw'] = '%d月%d日%.2d:%.2d',
		['en'] = '%dMonth%dDay%.2d: %.2d',
	},
	[159] = {
		['cn'] = '当前版本号：%s',
		['tw'] = '當前版本號：%s',
		['en'] = 'Current Version: %s',
	},
	[160] = {
		['cn'] = '最新版本号：%s',
		['tw'] = '最新版本號：%s',
		['en'] = 'Latest Version: %s',
	},
	[161] = {
		['cn'] = '倒计时：#cg%s#n',
		['tw'] = '倒數計時：#cg%s#n',
		['en'] = 'Countdown:  #cg%s#n',
	},
	[162] = {
		['cn'] = '倒计时：#cr%s#n',
		['tw'] = '倒數計時：#cr%s#n',
		['en'] = 'Countdown:  #cr%s#n',
	},
	[163] = {
		['cn'] = '#c613701CD：#n#c282aaf%d秒#n',
		['tw'] = '#c613701CD：#n#c282aaf%d秒#n',
		['en'] = '#c613701CD: #n#c282aaf%dseconds#n',
	},
	[164] = {
		['cn'] = '正在更新 %d%%[%s/%s]',
		['tw'] = '正在更新 %d%%[%s/%s]',
		['en'] = 'Updating%d%%[%s/%s]',
	},
	[165] = {
		['cn'] = '黑球：+?',
		['tw'] = '黑球：+?',
		['en'] = 'Black Ball: +?',
	},
	[166] = {
		['cn'] = '消灭',
		['tw'] = '消滅',
		['en'] = 'Eliminated',
	},
	[167] = {
		['cn'] = '缺少%d点体力',
		['tw'] = '缺少%d點體力',
		['en'] = '%d energy point more is needed',
	},
	[168] = {
		['cn'] = '关卡',
		['tw'] = '關卡',
		['en'] = 'Level',
	},
	[169] = {
		['cn'] = '关卡模式',
		['tw'] = '關卡模式',
		['en'] = 'Level Mode',
	},
	[170] = {
		['cn'] = '乱斗3级开放',
		['tw'] = '亂鬥3級開放',
		['en'] = 'Melee Mode to be unlocked in level 3',
	},
	[171] = {
		['cn'] = '派出你的兵球进攻蓝色母球',
		['tw'] = '派出你的兵球進攻藍色母球',
		['en'] = 'Send your Soldier Balls to attack the blue Mother Ball',
	},
	[172] = {
		['cn'] = '灰色母球是中立阵营，可以消耗4个兵球开垦他',
		['tw'] = '灰色母球是中立陣營，可以消耗4個兵球開墾他',
		['en'] = 'Reclaim the Neutral Mother Ball by consuming 4 Soldier Balls',
	},
	[173] = {
		['cn'] = '向其他方向滑动以停止派兵',
		['tw'] = '向其他方向滑動以停止派兵',
		['en'] = 'Drag to the other way to stop sending',
	},
	[174] = {
		['cn'] = '积累优势，消灭黄色势力，获得胜利',
		['tw'] = '積累優勢，消滅黃色勢力，獲得勝利',
		['en'] = 'To win the game,continue playing until the yellow camp is eliminated',
	},
	[175] = {
		['cn'] = '最多只能携带6个技能',
		['tw'] = '最多只能攜帶6個技能',
		['en'] = 'You can only carry 6 skills at most',
	},
	[186] = {
		['cn'] = '技能系统已开启！你获得了新技能！',
		['tw'] = '技能系統已開啟！你獲得了新技能！',
		['en'] = 'Skill system is opened!New skills have been obtained!',
	},
	[187] = {
		['cn'] = '点击技能',
		['tw'] = '點擊技能',
		['en'] = 'Click the skill button',
	},
	[188] = {
		['cn'] = '将已解锁的技能拖至技能槽',
		['tw'] = '將已解鎖的技能拖至技能槽',
		['en'] = 'Put your skill unlocked to the skill slot',
	},
	[189] = {
		['cn'] = '点选技能',
		['tw'] = '點選技能',
		['en'] = 'Select the skill',
	},
	[190] = {
		['cn'] = '点击母球施放技能',
		['tw'] = '點擊母球施放技能',
		['en'] = 'Cast skill by clicking the mother ball',
	},
	[191] = {
		['cn'] = '乱斗模式开启，你可以与线上其他玩家一起游戏！',
		['tw'] = '亂鬥模式開啟，你可以與線上其他玩家一起遊戲！',
		['en'] = 'Melee mode has been opened,you can play with other players online!',
	},
	[192] = {
		['cn'] = '升级功能还未开启',
		['tw'] = '陞級功能還未開啟',
		['en'] = 'The function of upgrade is not opened',
	},
	[193] = {
		['cn'] = '点击母球',
		['tw'] = '點擊母球',
		['en'] = 'Click the mother ball',
	},
	[194] = {
		['cn'] = '消耗6个兵球升级母球，获得狙击效果',
		['tw'] = '消耗6個兵球陞級母球，獲得狙擊效果',
		['en'] = 'Upgrade the Mother Ball to be a Sniper tower by consuming 6 Soldier Balls',
	},
	[195] = {
		['cn'] = '成功占领敌方母球，再次派出兵球',
		['tw'] = '成功佔領敵方母球，再次派出兵球',
		['en'] = 'Occupy the Hostile Mother Ball successfully,sent your Soldier Balls to attack again',
	},
	[196] = {
		['cn'] = '继续将你的兵球派往前线',
		['tw'] = '繼續將你的兵球派往前線',
		['en'] = 'Keep on sending your Soldier Balls to the front',
	},
	[197] = {
		['cn'] = '你获得了新技能！',
		['tw'] = '你獲得了新技能！',
		['en'] = 'New skills have been obtained!',
	},
	[198] = {
		['cn'] = '游戏目标：消灭除你之外的其他颜色小球！',
		['tw'] = '游戏目標：消滅除你之外的其他顏色小球！',
		['en'] = 'Mission Object:Eliminate all the other colour balls except yourself',
	},
	[1001] = {
		['cn'] = '批量生产',
		['tw'] = '批量生產',
		['en'] = 'Multitude',
	},
	[1002] = {
		['cn'] = '后备增援',
		['tw'] = '後備增援',
		['en'] = 'Reinforce',
	},
	[1003] = {
		['cn'] = '干涉',
		['tw'] = '干涉',
		['en'] = 'Interfere',
	},
	[1004] = {
		['cn'] = '半衰期',
		['tw'] = '半衰期',
		['en'] = 'Half-life',
	},
	[1005] = {
		['cn'] = '空投',
		['tw'] = '空投',
		['en'] = 'Airdrop',
	},
	[1006] = {
		['cn'] = '同化',
		['tw'] = '同化',
		['en'] = 'Assimilate',
	},
	[1007] = {
		['cn'] = '量子跃迁',
		['tw'] = '量子躍遷',
		['en'] = 'Ascending',
	},
	[1008] = {
		['cn'] = '离解',
		['tw'] = '離解',
		['en'] = 'Dissociation',
	},
	[1009] = {
		['cn'] = '菁华萃取',
		['tw'] = '菁華萃取',
		['en'] = 'Extraction',
	},
	[1010] = {
		['cn'] = '孤立',
		['tw'] = '孤立',
		['en'] = 'Isolation',
	},
	[1011] = {
		['cn'] = '碳化',
		['tw'] = '碳化',
		['en'] = 'Carbonization',
	},
	[1012] = {
		['cn'] = '路径燃烧',
		['tw'] = '路徑燃燒',
		['en'] = 'Combustion',
	},
	[1013] = {
		['cn'] = '策反',
		['tw'] = '策反',
		['en'] = 'Mutiny',
	},
	[1014] = {
		['cn'] = '煽动',
		['tw'] = '煽動',
		['en'] = 'Incite',
	},
	[1015] = {
		['cn'] = '弃子',
		['tw'] = '弃子',
		['en'] = 'Sacrifice',
	},
	[1016] = {
		['cn'] = '曲速前进',
		['tw'] = '曲速前進',
		['en'] = 'Topspeed',
	},
	[1017] = {
		['cn'] = '瘟疫爆发',
		['tw'] = '瘟疫爆發',
		['en'] = 'Plague',
	},
	[1018] = {
		['cn'] = '障眼法',
		['tw'] = '障眼法',
		['en'] = 'Cover-up',
	},
	[1019] = {
		['cn'] = '共生',
		['tw'] = '共生',
		['en'] = 'Symbiosis',
	},
	[1020] = {
		['cn'] = '信仰根除',
		['tw'] = '信仰根除',
		['en'] = 'Eradication',
	},
	[1021] = {
		['cn'] = '癌变',
		['tw'] = '癌變',
		['en'] = 'Canceration',
	},
	[1022] = {
		['cn'] = '大饥荒',
		['tw'] = '大饑荒',
		['en'] = 'Famine',
	},
	[1023] = {
		['cn'] = '驱虎吞狼',
		['tw'] = '驅虎吞狼',
		['en'] = 'Demagogue',
	},
	[1024] = {
		['cn'] = '收割',
		['tw'] = '收割',
		['en'] = 'Harvest',
	},
	[1025] = {
		['cn'] = '剿灭',
		['tw'] = '剿滅',
		['en'] = 'Extermination',
	},
	[1026] = {
		['cn'] = '意外失踪',
		['tw'] = '意外失踪',
		['en'] = 'Disappearance',
	},
	[1027] = {
		['cn'] = '进化',
		['tw'] = '進化',
		['en'] = 'Evolution',
	},
	[1028] = {
		['cn'] = '斩断血脉',
		['tw'] = '斬斷血脈',
		['en'] = 'Cut-off',
	},
	[1029] = {
		['cn'] = '伺机潜入',
		['tw'] = '伺機潜入',
		['en'] = 'Sneak',
	},
	[1030] = {
		['cn'] = '高筑墙',
		['tw'] = '高築牆',
		['en'] = 'Evolving Barrier',
	},
	[1031] = {
		['cn'] = '无人区',
		['tw'] = '無人區',
		['en'] = 'No Man\'s Land',
	},
	[1032] = {
		['cn'] = '叛逃',
		['tw'] = '叛逃',
		['en'] = 'Defection',
	},
	[1033] = {
		['cn'] = '时间停止',
		['tw'] = '時間停止',
		['en'] = 'Time stop',
	},
	[1034] = {
		['cn'] = '虫洞',
		['tw'] = '蟲洞',
		['en'] = 'Wormhole',
	},
	[1035] = {
		['cn'] = '回溯',
		['tw'] = '回溯',
		['en'] = 'Flash back',
	},
	[1036] = {
		['cn'] = '航运',
		['tw'] = '航運',
		['en'] = 'Shipping',
	},
	[1101] = {
		['cn'] = '#c613701施放目标：#n#c048d24我方母球#n',
		['tw'] = '#c613701施放目標：#n#c048d24我方母球#n',
		['en'] = '#c613701Target:#n#c048d24Your Mother Ball#n',
	},
	[1102] = {
		['cn'] = '#c613701施放目标：#n#c048d24我方1级母球#n',
		['tw'] = '#c613701施放目標：#n#c048d24我方1級母球#n',
		['en'] = '#c613701Target:#n#c048d24Your Mother Ball with Level 1#n',
	},
	[1103] = {
		['cn'] = '#c613701施放目标：#n#c048d24我方或中立母球#n',
		['tw'] = '#c613701施放目標：#n#c048d24我方或中立母球#n',
		['en'] = '#c613701Target:#n#c048d24Neutral or Your Mother Ball#n',
	},
	[1104] = {
		['cn'] = '#c613701施放目标：#n#cae2500敌方1级以上母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500敵方1級以上母球#n',
		['en'] = '#c613701Target:#n#cae2500Hostile Mother Ball with Level 2 or 3#n',
	},
	[1105] = {
		['cn'] = '#c613701施放目标：#n#c8300cf任意母球#n',
		['tw'] = '#c613701施放目標：#n#c8300cf任意母球#n',
		['en'] = '#c613701Target:#n#c8300cfAny Mother Ball#n',
	},
	[1106] = {
		['cn'] = '#c613701施放目标：#n#c535955中立母球#n',
		['tw'] = '#c613701施放目標：#n#c535955中立母球#n',
		['en'] = '#c613701Target:#n#c535955Neutral Mother Ball#n',
	},
	[1107] = {
		['cn'] = '#c613701施放目标：#n#c048d24我方3级以下母球#n',
		['tw'] = '#c613701施放目標：#n#c048d24我方3級以下母球#n',
		['en'] = '#c613701Target:#n#c048d24Your Mother Ball with Level 1 or 2#n',
	},
	[1108] = {
		['cn'] = '#c613701施放目标：#n#c048d24我方1级以上母球#n',
		['tw'] = '#c613701施放目標：#n#c048d24我方1級以上母球#n',
		['en'] = '#c613701Target:#n#c048d24Your Mother Ball with Level 2 or 3#n',
	},
	[1111] = {
		['cn'] = '#c613701施放目标：#n#cae2500敌方母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500敵方母球#n',
		['en'] = '#c613701Target:#n#cae2500Hostile Mother Ball#n',
	},
	[1114] = {
		['cn'] = '#c613701施放目标：#n#cae2500敌方3级以下母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500敵方3級以下母球#n',
		['en'] = '#c613701Target:#n#cae2500Hostile Mother Ball with Level 1 or 2#n',
	},
	[1120] = {
		['cn'] = '#c613701施放目标：#n#cae2500敌方1级母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500敵方1級母球#n',
		['en'] = '#c613701Target:#n#cae2500Hostile Mother Ball with Level 1#n',
	},
	[1126] = {
		['cn'] = '#c613701施放目标：#n#cae2500敌方或中立母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500敵方或中立母球#n',
		['en'] = '#c613701Target:#n#cae2500Hostile or Neutral Mother Ball#n',
	},
	[1128] = {
		['cn'] = '#c613701施放目标：#n#c8300cf我方或敌方母球#n',
		['tw'] = '#c613701施放目標：#n#c8300cf我方或敵方母球#n',
		['en'] = '#c613701Target:#n#c8300cfHostile or Your Mother Ball#n',
	},
	[1129] = {
		['cn'] = '#c613701施放目标：#n#cae2500中立或敌方1级母球#n',
		['tw'] = '#c613701施放目標：#n#cae2500中立或敵方1級母球#n',
		['en'] = '#c613701Target:#n#cae2500Neutral or Hostile Mother Ball with level 1#n',
	},
	[1201] = {
		['cn'] = '#c3c3114附近所有同阵营母球的造兵速度提高至4倍，持续8秒#n',
		['tw'] = '#c3c3114附近所有同陣營母球的造兵速度提高至4倍，持續8秒#n',
		['en'] = '#c3c3114Raise the growth rate of adjacent allied soldier ball up to 4 times,last for 8 seconds#n',
	},
	[1202] = {
		['cn'] = '#c3c3114将该母球上的兵力补至上限#n',
		['tw'] = '#c3c3114將該母球上的兵力補至上限#n',
		['en'] = '#c3c3114Fill it up with soldier ball#n',
	},
	[1203] = {
		['cn'] = '#c3c3114在该母球上派出8个中立兵球#n',
		['tw'] = '#c3c3114在該母球上派出8個中立兵球#n',
		['en'] = '#c3c3114Create 8 neutral soldier balls on it#n',
	},
	[1204] = {
		['cn'] = '#c3c3114消灭该母球上50%的兵力，并使其下降1级#n',
		['tw'] = '#c3c3114消滅該母球上50%的兵力，並使其下降1級#n',
		['en'] = '#c3c3114Kill 50% of the soldier balls on it,1 level down#n',
	},
	[1205] = {
		['cn'] = '#c3c3114在任意母球上派出4个己方兵球#n',
		['tw'] = '#c3c3114在任意母球上派出4個己方兵球#n',
		['en'] = '#c3c3114Create 4 soldier balls on your side on it#n',
	},
	[1206] = {
		['cn'] = '#c3c3114使该母球以及上面的兵球成为我方阵营#n',
		['tw'] = '#c3c3114使該母球以及上面的兵球成為我方陣營#n',
		['en'] = '#c3c3114Convert the mother ball and the soldier balls on it to our side#n',
	},
	[1207] = {
		['cn'] = '#c3c3114使该母球立即提升1级，本次升级不会获得技能点#n',
		['tw'] = '#c3c3114使該母球立即提升1級，本次陞級不會獲得技能點#n',
		['en'] = '#c3c3114 1 level up immediately without skill point#n',
	},
	[1208] = {
		['cn'] = '#c3c3114将该母球降低1级，然后派出10个己方兵球#n',
		['tw'] = '#c3c3114將該母球降低1級，然後派出10個己方兵球#n',
		['en'] = '#c3c3114 1 level down and create 10 soldier balls on your side#n',
	},
	[1209] = {
		['cn'] = '#c3c3114获得等同于该母球上兵力的技能点数#n',
		['tw'] = '#c3c3114獲得等同於該母球上兵力的技能點數#n',
		['en'] = '#c3c3114You gain skill point equal to the number of soldier ball on it#n',
	},
	[1210] = {
		['cn'] = '#c3c3114将该母球周围的道路斩断，15秒后重新长出#n',
		['tw'] = '#c3c3114將該母球周圍的道路斬斷，15秒後重新長出#n',
		['en'] = '#c3c3114Cut the path off near it,last for 15 seconds#n',
	},
	[1211] = {
		['cn'] = '#c3c3114将该母球变为黑球#n',
		['tw'] = '#c3c3114將該母球變為黑球#n',
		['en'] = '#c3c3114Transform it to black ball#n',
	},
	[1212] = {
		['cn'] = '#c3c3114让该母球周围的所有道路燃烧起来。兵球有较大几率死亡，持续6秒#n',
		['tw'] = '#c3c3114讓該母球周圍的所有道路燃燒起來。兵球有較大幾率死亡，持續6秒#n',
		['en'] = '#c3c3114Burn the path to kill the soldier balls near it,last for 6 seconds#n',
	},
	[1213] = {
		['cn'] = '#c3c3114让所有正在进攻该母球的兵球变为我方阵营#n',
		['tw'] = '#c3c3114讓所有正在進攻該母球的兵球變為我方陣營#n',
		['en'] = '#c3c3114Convert the soldier balls invading you to your camp#n',
	},
	[1214] = {
		['cn'] = '#c3c3114消灭该母球上的兵球，并使其提升1级#n',
		['tw'] = '#c3c3114消滅該母球上的兵球，並使其提升1級#n',
		['en'] = '#c3c3114Upgrade it for 1 level by all soldier balls consumed#n',
	},
	[1215] = {
		['cn'] = '#c3c3114将该母球变为原始中立母球，并产满中立兵球，然后获得18点技能点#n',
		['tw'] = '#c3c3114將該母球變為原始中立母球，並產滿中立兵球，然後獲得18點技能點#n',
		['en'] = '#c3c3114Convert it to neutral camp full of soldier balls,you gain 18 skill point#n',
	},
	[1216] = {
		['cn'] = '#c3c3114将附近道路上的兵球移动速度提高至5倍，持续6秒#n',
		['tw'] = '#c3c3114將附近道路上的兵球移動速度提高至5倍，持續6秒#n',
		['en'] = '#c3c3114Accelerate soldier balls near it by up to 5 times,last for 6 seconds#n',
	},
	[1217] = {
		['cn'] = '#c3c3114消灭该母球和附近母球上70%的兵力#n',
		['tw'] = '#c3c3114消滅該母球和附近母球上70%的兵力#n',
		['en'] = '#c3c3114Kill 70% of the soldier balls on it and adjacent mother balls#n',
	},
	[1218] = {
		['cn'] = '#c3c311430秒内，让其他人无法看清该母球及周围的真实情况，也不能对其施放技能#n',
		['tw'] = '#c3c311430秒內，讓其他人無法看清該母球及周圍的真實情况，也不能對其施放技能#n',
		['en'] = '#c3c3114Make all mother balls near it invisible to your opponents,and can\'t be the target for skill,last for 30 seconds#n',
	},
	[1219] = {
		['cn'] = '#c3c3114使该母球上的敌方兵力增加70%，每增加1个兵球，你获得2点技能点#n',
		['tw'] = '#c3c3114使該母球上的敵方兵力新增70%，每新增1個兵球，你獲得2點技能點#n',
		['en'] = '#c3c3114Increase the number of soldier ball on it by 70%,you gain 2 skill point for each soldier ball created this way#n',
	},
	[1220] = {
		['cn'] = '#c3c3114将该母球以及上面的兵球变为中立阵营，若其正在升级，将被停止#n',
		['tw'] = '#c3c3114將該母球以及上面的兵球變為中立陣營，若其正在陞級，將被停止#n',
		['en'] = '#c3c3114Convert the mother ball and the soldier balls on it to neutral camp,interrupt the upgrading if it is#n',
	},
	[1221] = {
		['cn'] = '#c3c3114向周围通往其它阵营的道路上派出等同于该母球上数量的兵力，然后将其变成黑球#n',
		['tw'] = '#c3c3114向周圍通往其它陣營的道路上派出等同於該母球上數量的兵力，然後將其變成黑球#n',
		['en'] = '#c3c3114Create a number of soldier balls of your own on each path to different camp, and the number equals to the number of soldier ball on it. Transform it to cyst#n',
	},
	[1222] = {
		['cn'] = '#c3c3114使该母球及周围的敌方母球停止造兵，且兵球不断死亡，持续12秒#n',
		['tw'] = '#c3c3114使該母球及周圍的敵方母球停止造兵，且兵球不斷死亡，持續12秒#n',
		['en'] = '#c3c3114Exchange the soldier ball increasing to deceasing of the mother ball and nearby,last for 12 seconds#n',
	},
	[1223] = {
		['cn'] = '#c3c3114消灭该母球上的所有兵球，然后向周围通往其它阵营道路上各派出等量的兵力#n',
		['tw'] = '#c3c3114消滅該母球上的所有兵球，然後向周圍通往其它陣營道路上各派出等量的兵力#n',
		['en'] = '#c3c3114Kill all the soldier balls on it,create a same number of soldier balls on each path to the mother ball in different camp#n',
	},
	[1224] = {
		['cn'] = '#c3c3114消灭该母球上的所有兵球，每消灭1个，你获得2点技能点#n',
		['tw'] = '#c3c3114消滅該母球上的所有兵球，每消滅1個，你獲得2點技能點#n',
		['en'] = '#c3c3114Kill all the soldier balls. For each soldier ball killed in this way, you gain 2 skill point#n',
	},
	[1225] = {
		['cn'] = '#c3c3114消灭该母球上的所有中立和敌方兵球#n',
		['tw'] = '#c3c3114消滅該母球上的所有中立和敵方兵球#n',
		['en'] = '#c3c3114Kill all the soldier balls expect your own#n',
	},
	[1226] = {
		['cn'] = '#c3c3114消灭该母球上6个兵球#n',
		['tw'] = '#c3c3114消滅該母球上6個兵球#n',
		['en'] = '#c3c3114Kill 6 soldier balls on it#n',
	},
	[1227] = {
		['cn'] = '#c3c3114不消耗兵力直接使母球进入升级状态#n',
		['tw'] = '#c3c3114不消耗兵力直接使母球進入陞級狀態#n',
		['en'] = '#c3c3114Start upgrading without consuming soldier balls#n',
	},
	[1228] = {
		['cn'] = '#c3c3114将其与同阵营母球相连的道路斩断，10秒后重新长出#n',
		['tw'] = '#c3c3114將其與同陣營母球相連的道路斬斷，10秒後重新長出#n',
		['en'] = '#c3c3114Cut off the path connect to the same camp near it,last for 10 seconds#n',
	},
	[1229] = {
		['cn'] = '#c3c3114在周围每个敌方和中立母球上各派出5个我方兵球#n',
		['tw'] = '#c3c3114在周圍每個敵方和中立母球上各派出5個我方兵球#n',
		['en'] = '#c3c3114Create 5 soldier balls on each hostile or neutral mother ball near it#n',
	},
	[1230] = {
		['cn'] = '#c3c3114在周围每个中立母球上各生出5个中立兵球#n',
		['tw'] = '#c3c3114在周圍每個中立母球上各生出5個中立兵球#n',
		['en'] = '#c3c3114Create 6 neutral soldier balls on each neutral mother ball near it#n',
	},
	[1231] = {
		['cn'] = '#c3c3114消灭其与周围其它阵营母球上的所有兵球#n',
		['tw'] = '#c3c3114消滅其與周圍其它陣營母球上的所有兵球#n',
		['en'] = '#c3c3114Kill all the soldier balls on it and the mother balls nearby except of your own#n',
	},
	[1232] = {
		['cn'] = '#c3c3114使该母球周围道路上的兵球变为中立阵营#n',
		['tw'] = '#c3c3114使該母球周圍道路上的兵球變為中立陣營#n',
		['en'] = '#c3c3114Convert the soldier balls on nearby path to neutral camp#n',
	},
	[1233] = {
		['cn'] = '#c3c3114使该母球停止产兵，周围的兵球停止移动，持续8秒#n',
		['tw'] = '#c3c3114使該母球停止產兵，周圍的兵球停止移動，持續8秒#n',
		['en'] = '#c3c3114Stop the mother ball from producing,stop surrounding soldier balls from moving,last for 8 seconds#n',
	},
	[1234] = {
		['cn'] = '#c3c3114使我方兵球随机传送至该母球上，持续10秒#n',
		['tw'] = '#c3c3114使我方兵球隨機傳送至該母球上，持續10秒#n',
		['en'] = '#c3c3114Randomly transfer your soldier balls to the mother ball,last for 10 seconds#n',
	},
	[1235] = {
		['cn'] = '#c3c31148秒后，该母球及其上面兵球的状态和数量都重新回到8秒前的模样#n',
		['tw'] = '#c3c31148秒後，該母球及其上面兵球的狀態和數量都重新回到8秒前的模樣#n',
		['en'] = '#c3c3114After 8 seconds,recover the number and status of the mother ball and soldier balls nearby#n',
	},
	[1236] = {
		['cn'] = '#c3c3114使该母球上的兵球可以派至任意母球，持续10秒#n',
		['tw'] = '#c3c3114使該母球上的兵球可以派至任意母球，持續10秒#n',
		['en'] = '#c3c3114Enable the soldier balls on the mother ball to be sent to any mother ball,last for 10 seconds#n',
	},
	[2000] = {
		['cn'] = '《细胞大作战》是一款多人同时在线的休闲竞技游戏。用最简洁的元素，传达最直观的概念；以最深度的策略，构造最上瘾的玩法！在一次紧张刺激的对局中体会前所未有的战略快感！－－游戏特色－－＊将复杂的战争策略用最简洁，直白的方式呈现出来。每个人都是战略家，分配你的资源，扩充你的势力，应对纷乱繁杂的场面。认清敌我形势，机会转瞬即逝，战争就是一盘棋局！＊合理运用你的兵球，在正确的时机，选择占领，建设，进攻，还是防守！消灭所有其他玩家，获得最后胜利！＊无数值养成，无氪金！绝对公平竞技！＊二十种强力技能，随意搭配，助你逆转局势！－－尽情期待－－＊组队模式。带上你的好友，一起参加2v2v2，3v3等多种玩法，一起享受纸上谈兵的乐趣！＊天梯排位赛。拥有更激烈的竞争，更残酷的角逐！＊皮肤系统。让你的球球更养颜，更有个性。最后，求加入！求好评！',
		['tw'] = '《細胞大作戰》是一款多人同時線上的休閒競技遊戲。用最簡潔的元素，傳達最直觀的概念；以最深度的策略，構造最上癮的玩法！在一次緊張刺激的對局中體會前所未有的戰畧快感！－－遊戲特色－－＊將複雜的戰爭策略用最簡潔，直白的管道呈現出來。每個人都是戰略家，分配你的資源，擴充你的勢力，應對紛亂繁雜的場面。認清敵我形勢，機會轉瞬即逝，戰爭就是一盤棋局！＊合理運用你的兵球，在正確的時機，選擇佔領，建設，侵略，還是防守！消滅所有其他玩家，獲得最後勝利！＊無數值養成，無氪金！絕對公平競技！＊二十種强力技能，隨意搭配，助你逆轉局勢！－－盡情期待－－＊組隊模式。帶上你的好友，一起參加2v2v2，3v3等多種玩法，一起享受紙上談兵的樂趣！＊天梯排位賽。擁有更激烈的競爭，更殘酷的角逐！＊皮膚系統。讓你的球球更養顏，更有個性。最後，求加入！求好評！',
		['en'] = '"Cell.io" is a multiplayer online competitive game, which conveys the most intuitive concept with the most simple elements and constructs the most addictive gameplay with the most in-depth strategy! You will experience unprecedented strategic pleasure in this exciting game!- Game Features -* Presenting complex battle strategy with the most simple, straightforward way. Everyone is a strategist. Allocate your resources, expand your forces, and deal with complex scenarios. Realize enemy\'s situation and catch every opportunity to win. War is a chess game!* Appropriately use your balls to occupy, construct, attack, or defend! Eliminate all other players to win the battle!* No character development, no burning cash! Absolute fair play!* 20 kinds of powerful skills that can be mixed at will to help you reverse the situation!- Expectations -* Team mode. Bring your friends together to participate in 2v2v2, 3v3 and other gameplays. Enjoy the fun on battle!* Ranking battle with more intense competition and more brutal fight!* Skin system. Let your ball more beautiful and more personalized.Finally, please join and welcome your comments!',
	},
})
