-- ------------------------------
-- desc: generated by xls2data.py
-- source: club_config.xlsx
-- sheet: 俱乐部消息
-- ------------------------------


data = table.protect({
	[1] = {
		['template'] = '#co{nickname}({user_id})#n请求加入俱乐部<#co{club_name}({club_id})#n>，并留言：{left_words}。',
	},
	[2] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员#cg通过了#n您的申请。',
	},
	[3] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员#cr拒绝了#n您的申请#n。',
	},
	[4] = {
		['template'] = '#co{nickname}({user_id})#n向俱乐部<#co{club_name}({club_id})#n>捐赠#cy{gold_coin_count}#cn金豆。',
	},
	[5] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员#cg接受了#n您捐赠的#cy{gold_coin_count}#n金豆。',
	},
	[6] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员#cr退回了#n您捐赠的#cy{gold_coin_count}#n金豆。',
	},
	[7] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员给您#cg发放了#n#cy{gold_coin_count}#n金豆。',
	},
	[8] = {
		['template'] = '#co{nickname}({user_id})#n#cr离开了#n俱乐部<#co{club_name}({club_id})#n>。',
	},
	[9] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>已经解散，您最后在该俱乐部还有#cy{gold_coin_count}#n金豆未使用。',
	},
	[10] = {
		['template'] = '俱乐部<#co{club_name}({club_id})#n>管理员将您#cr踢出了#n俱乐部，您最后在该俱乐部还有#cy{gold_coin_count}#n金豆未使用。',
	},
})
