-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 平和麻将内购
-- ------------------------------


data = table.protect({
	['roomcards1'] = {
		['price'] = 600,
		['store_price'] = 600,
		['name'] = TEXT('钻石x%d'),
		['num'] = 3,
	},
	['roomcards2'] = {
		['price'] = 3000,
		['store_price'] = 3000,
		['name'] = TEXT('钻石x%d'),
		['num'] = 15,
	},
	['roomcards3'] = {
		['price'] = 9800,
		['store_price'] = 9800,
		['name'] = TEXT('钻石x%d'),
		['num'] = 50,
	},
})
