-- ------------------------------
-- desc: generated by xls2data.py
-- source: poker_rules.xlsx
-- sheet: 牛牛
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_10;round_20',
		['defaultMenu'] = 'round_10',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('模式'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'niuniu_jingdian;niuniu_jiabei',
		['defaultMenu'] = 'niuniu_jiabei',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('坐庄'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'zhuang_qiang;zhuang_lun',
		['defaultMenu'] = 'zhuang_qiang',
		['isHide'] = 0,
	},
})
