-- ------------------------------
-- desc: generated by xls2data.py
-- source: poker_rules.xlsx
-- sheet: 牌九-开庄玩法
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('开庄玩法'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_kzwf',
		['defaultMenu'] = 'paijiu_kzwf',
		['clubDefaultMenu'] = '',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('8点过套'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_bdgt',
		['defaultMenu'] = 'paijiu_bdgt',
		['clubDefaultMenu'] = '',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('可续庄1次'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_xz1c',
		['defaultMenu'] = 'paijiu_xz1c',
		['clubDefaultMenu'] = '',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT('坐庄'),
		['optionRanking'] = 4,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_banker_fixed;paijiu_banker_random',
		['defaultMenu'] = 'paijiu_banker_fixed',
		['clubDefaultMenu'] = 'paijiu_banker_random',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT('分数'),
		['optionRanking'] = 5,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_kz_100;paijiu_kz_200;paijiu_kz_500',
		['defaultMenu'] = 'paijiu_kz_200',
		['clubDefaultMenu'] = '',
		['isHide'] = 0,
	},
	[6] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 6,
		['optionType'] = 1,
		['optionMenu'] = 'paijiu_tianjiu_is_one;paijiu_tianjiu_is_wang',
		['defaultMenu'] = 'paijiu_tianjiu_is_wang',
		['clubDefaultMenu'] = '',
		['isHide'] = 0,
	},
})
