-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 平和麻将消耗
-- ------------------------------


data = table.protect({
	[0] = {
		['room_card_cost2'] = 24,
		['room_card_cost3'] = 24,
		['room_card_cost4'] = 24,
		['room_card_cost5'] = 24,
		['aa_round'] = 0,
	},
	[1] = {
		['room_card_cost2'] = 4,
		['room_card_cost3'] = 4,
		['room_card_cost4'] = 4,
		['room_card_cost5'] = 4,
		['aa_round'] = 0,
	},
	[2] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['room_card_cost5'] = 8,
		['aa_round'] = 0,
	},
	[3] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['room_card_cost5'] = 12,
		['aa_round'] = 0,
	},
	[4] = {
		['room_card_cost2'] = 16,
		['room_card_cost3'] = 16,
		['room_card_cost4'] = 16,
		['room_card_cost5'] = 16,
		['aa_round'] = 0,
	},
	[8] = {
		['room_card_cost2'] = 8,
		['room_card_cost3'] = 8,
		['room_card_cost4'] = 8,
		['room_card_cost5'] = 8,
		['aa_round'] = 0,
	},
	[10] = {
		['room_card_cost2'] = 40,
		['room_card_cost3'] = 40,
		['room_card_cost4'] = 40,
		['room_card_cost5'] = 40,
		['aa_round'] = 0,
	},
	[12] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['room_card_cost5'] = 12,
		['aa_round'] = 0,
	},
	[16] = {
		['room_card_cost2'] = 16,
		['room_card_cost3'] = 16,
		['room_card_cost4'] = 16,
		['room_card_cost5'] = 16,
		['aa_round'] = 0,
	},
	[20] = {
		['room_card_cost2'] = 80,
		['room_card_cost3'] = 80,
		['room_card_cost4'] = 80,
		['room_card_cost5'] = 80,
		['aa_round'] = 0,
	},
	[24] = {
		['room_card_cost2'] = 24,
		['room_card_cost3'] = 24,
		['room_card_cost4'] = 24,
		['room_card_cost5'] = 24,
		['aa_round'] = 0,
	},
})
