-- ------------------------------
-- desc: generated by xls2data.py
-- source: create_option.xlsx
-- sheet: 创建选项
-- ------------------------------


data = table.protect({
	[1] = {
		['gameType'] = 'hnzz',
		['createConfigFile'] = 'data/info/info_rule_hnzz.lua',
		['realGameType'] = '',
		['gameName'] = '转转麻将',
		['gameStyle'] = 1,
	},
	[2] = {
		['gameType'] = 'hzmj',
		['createConfigFile'] = 'data/info/info_rule_hzmj.lua',
		['realGameType'] = '',
		['gameName'] = '红中麻将',
		['gameStyle'] = 1,
	},
	[3] = {
		['gameType'] = 'tjmj',
		['createConfigFile'] = 'data/info/info_rule_tjmj.lua',
		['realGameType'] = '',
		['gameName'] = '桃江麻将',
		['gameStyle'] = 1,
	},
	[4] = {
		['gameType'] = 'dsmj',
		['createConfigFile'] = 'data/info/info_rule_dsmj.lua',
		['realGameType'] = '',
		['gameName'] = '东山麻将',
		['gameStyle'] = 1,
	},
	[5] = {
		['gameType'] = 'zamj',
		['createConfigFile'] = 'data/info/info_rule_zamj.lua',
		['realGameType'] = '',
		['gameName'] = '诏安麻将',
		['gameStyle'] = 1,
	},
	[6] = {
		['gameType'] = 'mmmj',
		['createConfigFile'] = 'data/info/info_rule_mmmj.lua',
		['realGameType'] = '',
		['gameName'] = '茂名麻将',
		['gameStyle'] = 1,
	},
	[7] = {
		['gameType'] = 'tjtjmj',
		['createConfigFile'] = 'data/info/info_rule_tjtjmj.lua',
		['realGameType'] = '',
		['gameName'] = '天津麻将',
		['gameStyle'] = 1,
	},
	[8] = {
		['gameType'] = 'yyhsz',
		['createConfigFile'] = 'data/info/info_rule_yunyang_huansanzhang.lua',
		['realGameType'] = '',
		['gameName'] = '云阳换三张',
		['gameStyle'] = 1,
	},
	[9] = {
		['gameType'] = 'cqddh',
		['createConfigFile'] = 'data/info/info_rule_daodaohu.lua',
		['realGameType'] = '',
		['gameName'] = '重庆倒倒胡',
		['gameStyle'] = 1,
	},
	[10] = {
		['gameType'] = 'kawuxing',
		['createConfigFile'] = 'data/info/info_rule_kawuxing.lua',
		['realGameType'] = '',
		['gameName'] = '卡五星',
		['gameStyle'] = 1,
	},
	[11] = {
		['gameType'] = 'sdrcmj',
		['createConfigFile'] = 'data/info/info_rule_sdrcmj.lua',
		['realGameType'] = '',
		['gameName'] = '荣成麻将',
		['gameStyle'] = 1,
	},
	[12] = {
		['gameType'] = 'xzdd',
		['createConfigFile'] = 'data/info/info_rule_xzdd.lua',
		['realGameType'] = '',
		['gameName'] = '血战到底',
		['gameStyle'] = 1,
	},
	[13] = {
		['gameType'] = 'baihekawuxing',
		['createConfigFile'] = 'data/info/info_rule_baihe_kawuxing.lua',
		['realGameType'] = '',
		['gameName'] = '白河卡五星',
		['gameStyle'] = 1,
	},
	[14] = {
		['gameType'] = 'niuniu',
		['createConfigFile'] = 'data/info/info_rule_niuniu.lua',
		['realGameType'] = 'niuniu',
		['gameName'] = '牛牛',
		['gameStyle'] = 2,
	},
	[15] = {
		['gameType'] = 'yy_niuniu',
		['createConfigFile'] = 'data/info/info_rule_yy_niuniu.lua',
		['realGameType'] = 'niuniu',
		['gameName'] = '牛牛',
		['gameStyle'] = 2,
	},
	[16] = {
		['gameType'] = 'paijiu_kzwf',
		['createConfigFile'] = 'data/info/info_rule_paijiu_kzwf.lua',
		['realGameType'] = 'paijiu_kzwf',
		['gameName'] = '牌九-开庄玩法',
		['gameStyle'] = 2,
	},
	[17] = {
		['gameType'] = 'paijiu_mpqz',
		['createConfigFile'] = 'data/info/info_rule_paijiu_mpqz.lua',
		['realGameType'] = 'paijiu_mpqz',
		['gameName'] = '牌九-明牌抢庄',
		['gameStyle'] = 2,
	},
	[18] = {
		['gameType'] = 'phmj',
		['createConfigFile'] = 'data/info/info_rule_phmj.lua',
		['realGameType'] = '',
		['gameName'] = '平和麻将',
		['gameStyle'] = 1,
	},
})
