-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 每日分享
-- ------------------------------


data = table.protect({
	['tj_lexian'] = {
		['room_card_count'] = 0,
		['room_card_count_max'] = 0,
		['gold_coin_count'] = 0,
		['interval'] = 0,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['openew'] = {
		['room_card_count'] = 0,
		['room_card_count_max'] = 0,
		['gold_coin_count'] = 0,
		['interval'] = 0,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['ds_queyue'] = {
		['room_card_count'] = 1,
		['room_card_count_max'] = 2,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = 'info_sharing_hongbao_ds_queyue',
		['redpacket_interval'] = 0,
	},
	['ph_queyue'] = {
		['room_card_count'] = 1,
		['room_card_count_max'] = 2,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = 'info_sharing_hongbao_ps_queyue',
		['redpacket_interval'] = 0,
	},
	['za_queyue'] = {
		['room_card_count'] = 1,
		['room_card_count_max'] = 2,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['test'] = {
		['room_card_count'] = 18,
		['room_card_count_max'] = 18,
		['gold_coin_count'] = 2,
		['interval'] = 3,
		['redpacket_count'] = 'info_sharing_hongbao_ds_queyue',
		['redpacket_interval'] = 1,
	},
	['ly_youwen'] = {
		['room_card_count'] = 0,
		['room_card_count_max'] = 0,
		['gold_coin_count'] = 0,
		['interval'] = 0,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['yy_doudou'] = {
		['room_card_count'] = 5,
		['room_card_count_max'] = 15,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['rc_xianle'] = {
		['room_card_count'] = 6,
		['room_card_count_max'] = 15,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['xy_hanshui'] = {
		['room_card_count'] = 0,
		['room_card_count_max'] = 0,
		['gold_coin_count'] = 0,
		['interval'] = 0,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['jz_laiba'] = {
		['room_card_count'] = 4,
		['room_card_count_max'] = 4,
		['gold_coin_count'] = 0,
		['interval'] = 2,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['nc_tianjiuwang'] = {
		['room_card_count'] = 2,
		['room_card_count_max'] = 2,
		['gold_coin_count'] = 0,
		['interval'] = 1,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
	['qs_pinghe'] = {
		['room_card_count'] = 0,
		['room_card_count_max'] = 0,
		['gold_coin_count'] = 0,
		['interval'] = 0,
		['redpacket_count'] = '',
		['redpacket_interval'] = 0,
	},
})
