-- ------------------------------
-- desc: generated by xls2data.py
-- source: club_config.xlsx
-- sheet: 俱乐部渠道配置
-- ------------------------------


data = table.protect({
	['test'] = {
		['max_club_count'] = 3,
		['room_card_cost1'] = 1,
		['room_card_cost2'] = 1,
		['max_member_count'] = 500,
		['max_ground_count'] = 10,
		['gold_coins_per_room_card'] = 100,
		['initial_gold_coin_count'] = 10000,
	},
	['openew'] = {
		['max_club_count'] = 3,
		['room_card_cost1'] = 100,
		['room_card_cost2'] = 2,
		['max_member_count'] = 500,
		['max_ground_count'] = 10,
		['gold_coins_per_room_card'] = 100,
		['initial_gold_coin_count'] = 2000,
	},
	['ly_youwen'] = {
		['max_club_count'] = 3,
		['room_card_cost1'] = 100,
		['room_card_cost2'] = 2,
		['max_member_count'] = 500,
		['max_ground_count'] = 10,
		['gold_coins_per_room_card'] = 100,
		['initial_gold_coin_count'] = 2000,
	},
	['nc_tianjiuwang'] = {
		['max_club_count'] = 2,
		['room_card_cost1'] = 100,
		['room_card_cost2'] = 6,
		['max_member_count'] = 500,
		['max_ground_count'] = 6,
		['gold_coins_per_room_card'] = 100,
		['initial_gold_coin_count'] = 2000,
	},
	['yy_doudou'] = {
		['max_club_count'] = 1,
		['room_card_cost1'] = 100,
		['room_card_cost2'] = 4,
		['max_member_count'] = 100,
		['max_ground_count'] = 2,
		['gold_coins_per_room_card'] = 100,
		['initial_gold_coin_count'] = 2000,
	},
})
