-- ------------------------------
-- desc: generated by xls2data.py
-- source: club_config.xlsx
-- sheet: 底注设置
-- ------------------------------


data = table.protect({
	['1'] = {
		['round_min_gold'] = 1,
		['ground_min_gold'] = 20,
	},
	['2'] = {
		['round_min_gold'] = 2,
		['ground_min_gold'] = 50,
	},
	['3'] = {
		['round_min_gold'] = 5,
		['ground_min_gold'] = 100,
	},
	['4'] = {
		['round_min_gold'] = 10,
		['ground_min_gold'] = 200,
	},
	['5'] = {
		['round_min_gold'] = 20,
		['ground_min_gold'] = 500,
	},
	['6'] = {
		['round_min_gold'] = 50,
		['ground_min_gold'] = 1000,
	},
	['7'] = {
		['round_min_gold'] = 100,
		['ground_min_gold'] = 2000,
	},
	['8'] = {
		['round_min_gold'] = 200,
		['ground_min_gold'] = 5000,
	},
	['9'] = {
		['round_min_gold'] = 500,
		['ground_min_gold'] = 10000,
	},
	['10'] = {
		['round_min_gold'] = 0,
		['ground_min_gold'] = 20000,
	},
	['11'] = {
		['round_min_gold'] = 0,
		['ground_min_gold'] = 50000,
	},
})
