-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: 荣城消耗
-- ------------------------------


data = table.protect({
	[4] = {
		['room_card_cost2'] = 15,
		['room_card_cost3'] = 15,
		['room_card_cost4'] = 15,
		['aa_round'] = 1,
	},
	[8] = {
		['room_card_cost2'] = 30,
		['room_card_cost3'] = 30,
		['room_card_cost4'] = 30,
		['aa_round'] = 1,
	},
	[12] = {
		['room_card_cost2'] = 12,
		['room_card_cost3'] = 12,
		['room_card_cost4'] = 12,
		['aa_round'] = 1,
	},
	[16] = {
		['room_card_cost2'] = 60,
		['room_card_cost3'] = 60,
		['room_card_cost4'] = 60,
		['aa_round'] = 1,
	},
})
