-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet: XZ血战到底
-- ------------------------------


data = table.protect({
	[1] = {
		['optionText1'] = TEXT('局数'),
		['optionRanking'] = 1,
		['optionType'] = 1,
		['optionMenu'] = 'round_4;round_8',
		['defaultMenu'] = 'round_8',
		['isHide'] = 0,
	},
	[2] = {
		['optionText1'] = TEXT('人数'),
		['optionRanking'] = 2,
		['optionType'] = 1,
		['optionMenu'] = 'player_4;player_3;player_2',
		['defaultMenu'] = 'player_3',
		['isHide'] = 0,
	},
	[3] = {
		['optionText1'] = TEXT('玩法'),
		['optionRanking'] = 3,
		['optionType'] = 1,
		['optionMenu'] = 'dingque;budingque;',
		['defaultMenu'] = 'dingque',
		['isHide'] = 0,
	},
	[4] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 4,
		['optionType'] = 1,
		['optionMenu'] = 'fengding_3;fengding_4;fengding_5',
		['defaultMenu'] = 'fengding_4',
		['isHide'] = 0,
	},
	[5] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 5,
		['optionType'] = 1,
		['optionMenu'] = 'lingfanqihu;yifanqihu;erfanqihu',
		['defaultMenu'] = 'lingfanqihu',
		['isHide'] = 0,
	},
	[6] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 6,
		['optionType'] = 3,
		['optionMenu'] = 'huansanzhang;zimojiadi;zimojiafan',
		['defaultMenu'] = 'huansanzhang;zimojiadi',
		['isHide'] = 0,
	},
	[7] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 7,
		['optionType'] = 3,
		['optionMenu'] = 'hujiaozhuanyi;dianganghua;tiandihu',
		['defaultMenu'] = 'hujiaozhuanyi;dianganghua',
		['isHide'] = 0,
	},
	[8] = {
		['optionText1'] = TEXT(''),
		['optionRanking'] = 8,
		['optionType'] = 3,
		['optionMenu'] = 'menqingzhongzhang;daiyaojiujiangdui;yitiaolong',
		['defaultMenu'] = '',
		['isHide'] = 0,
	},
})
