-- ------------------------------
-- desc: generated by xls2data.py
-- source: configure.xlsx
-- sheet:  优惠
-- ------------------------------


data = table.protect({
	['tj_lexian'] = {
		['rn_room_card_gift'] = 58,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 32,
		['bic_recharge_gift'] = 0.0,
	},
	['openew'] = {
		['rn_room_card_gift'] = 20,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 20,
		['bic_recharge_gift'] = 0.0,
	},
	['rc_xianle'] = {
		['rn_room_card_gift'] = 32,
		['rn_recharge_gift'] = 0.0,
		['bic_room_card_gift'] = 32,
		['bic_recharge_gift'] = 0.0,
	},
	['ds_queyue'] = {
		['rn_room_card_gift'] = 40,
		['rn_recharge_gift'] = 0.0,
		['bic_room_card_gift'] = 0,
		['bic_recharge_gift'] = 0.0,
	},
	['test'] = {
		['rn_room_card_gift'] = 0,
		['rn_recharge_gift'] = 0.0,
		['bic_room_card_gift'] = 0,
		['bic_recharge_gift'] = 0.0,
	},
	['ly_youwen'] = {
		['rn_room_card_gift'] = 20,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 20,
		['bic_recharge_gift'] = 0.0,
	},
	['yy_doudou'] = {
		['rn_room_card_gift'] = 58,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 32,
		['bic_recharge_gift'] = 0.0,
	},
	['xy_hanshui'] = {
		['rn_room_card_gift'] = 20,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 20,
		['bic_recharge_gift'] = 0.0,
	},
	['jz_laiba'] = {
		['rn_room_card_gift'] = 20,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 10,
		['bic_recharge_gift'] = 0.0,
	},
	['nc_tianjiuwang'] = {
		['rn_room_card_gift'] = 20,
		['rn_recharge_gift'] = 0.05,
		['bic_room_card_gift'] = 10,
		['bic_recharge_gift'] = 0.0,
	},
})
