-- ------------------------------
-- desc: generated by xls2data.py
-- source: club_config.xlsx
-- sheet: 城市
-- ------------------------------


data = table.protect({
	[1] = {
		['code'] = 1001,
		['name'] = TEXT('石家庄'),
		['province_code'] = 103,
	},
	[2] = {
		['code'] = 1002,
		['name'] = TEXT('唐山'),
		['province_code'] = 103,
	},
	[3] = {
		['code'] = 1003,
		['name'] = TEXT('秦皇岛'),
		['province_code'] = 103,
	},
	[4] = {
		['code'] = 1004,
		['name'] = TEXT('邯郸'),
		['province_code'] = 103,
	},
	[5] = {
		['code'] = 1005,
		['name'] = TEXT('邢台'),
		['province_code'] = 103,
	},
	[6] = {
		['code'] = 1006,
		['name'] = TEXT('保定'),
		['province_code'] = 103,
	},
	[7] = {
		['code'] = 1007,
		['name'] = TEXT('张家口'),
		['province_code'] = 103,
	},
	[8] = {
		['code'] = 1008,
		['name'] = TEXT('承德'),
		['province_code'] = 103,
	},
	[9] = {
		['code'] = 1009,
		['name'] = TEXT('沧州'),
		['province_code'] = 103,
	},
	[10] = {
		['code'] = 1010,
		['name'] = TEXT('廊坊'),
		['province_code'] = 103,
	},
	[11] = {
		['code'] = 1011,
		['name'] = TEXT('衡水'),
		['province_code'] = 103,
	},
	[12] = {
		['code'] = 1012,
		['name'] = TEXT('太原'),
		['province_code'] = 104,
	},
	[13] = {
		['code'] = 1013,
		['name'] = TEXT('大同'),
		['province_code'] = 104,
	},
	[14] = {
		['code'] = 1014,
		['name'] = TEXT('阳泉'),
		['province_code'] = 104,
	},
	[15] = {
		['code'] = 1015,
		['name'] = TEXT('长治'),
		['province_code'] = 104,
	},
	[16] = {
		['code'] = 1016,
		['name'] = TEXT('晋城'),
		['province_code'] = 104,
	},
	[17] = {
		['code'] = 1017,
		['name'] = TEXT('朔州'),
		['province_code'] = 104,
	},
	[18] = {
		['code'] = 1018,
		['name'] = TEXT('晋中'),
		['province_code'] = 104,
	},
	[19] = {
		['code'] = 1019,
		['name'] = TEXT('运城'),
		['province_code'] = 104,
	},
	[20] = {
		['code'] = 1020,
		['name'] = TEXT('忻州'),
		['province_code'] = 104,
	},
	[21] = {
		['code'] = 1021,
		['name'] = TEXT('临汾'),
		['province_code'] = 104,
	},
	[22] = {
		['code'] = 1022,
		['name'] = TEXT('吕梁'),
		['province_code'] = 104,
	},
	[23] = {
		['code'] = 1023,
		['name'] = TEXT('呼和浩特'),
		['province_code'] = 105,
	},
	[24] = {
		['code'] = 1024,
		['name'] = TEXT('包头'),
		['province_code'] = 105,
	},
	[25] = {
		['code'] = 1025,
		['name'] = TEXT('乌海'),
		['province_code'] = 105,
	},
	[26] = {
		['code'] = 1026,
		['name'] = TEXT('赤峰'),
		['province_code'] = 105,
	},
	[27] = {
		['code'] = 1027,
		['name'] = TEXT('通辽'),
		['province_code'] = 105,
	},
	[28] = {
		['code'] = 1028,
		['name'] = TEXT('鄂尔多斯'),
		['province_code'] = 105,
	},
	[29] = {
		['code'] = 1029,
		['name'] = TEXT('呼伦贝尔'),
		['province_code'] = 105,
	},
	[30] = {
		['code'] = 1030,
		['name'] = TEXT('巴彦淖尔'),
		['province_code'] = 105,
	},
	[31] = {
		['code'] = 1031,
		['name'] = TEXT('乌兰察布'),
		['province_code'] = 105,
	},
	[32] = {
		['code'] = 1032,
		['name'] = TEXT('兴安盟'),
		['province_code'] = 105,
	},
	[33] = {
		['code'] = 1033,
		['name'] = TEXT('锡林郭勒'),
		['province_code'] = 105,
	},
	[34] = {
		['code'] = 1034,
		['name'] = TEXT('阿拉善'),
		['province_code'] = 105,
	},
	[35] = {
		['code'] = 1035,
		['name'] = TEXT('沈阳'),
		['province_code'] = 106,
	},
	[36] = {
		['code'] = 1036,
		['name'] = TEXT('大连'),
		['province_code'] = 106,
	},
	[37] = {
		['code'] = 1037,
		['name'] = TEXT('鞍山'),
		['province_code'] = 106,
	},
	[38] = {
		['code'] = 1038,
		['name'] = TEXT('抚顺'),
		['province_code'] = 106,
	},
	[39] = {
		['code'] = 1039,
		['name'] = TEXT('本溪'),
		['province_code'] = 106,
	},
	[40] = {
		['code'] = 1040,
		['name'] = TEXT('丹东'),
		['province_code'] = 106,
	},
	[41] = {
		['code'] = 1041,
		['name'] = TEXT('锦州'),
		['province_code'] = 106,
	},
	[42] = {
		['code'] = 1042,
		['name'] = TEXT('营口'),
		['province_code'] = 106,
	},
	[43] = {
		['code'] = 1043,
		['name'] = TEXT('阜新'),
		['province_code'] = 106,
	},
	[44] = {
		['code'] = 1044,
		['name'] = TEXT('辽阳'),
		['province_code'] = 106,
	},
	[45] = {
		['code'] = 1045,
		['name'] = TEXT('盘锦'),
		['province_code'] = 106,
	},
	[46] = {
		['code'] = 1046,
		['name'] = TEXT('铁岭'),
		['province_code'] = 106,
	},
	[47] = {
		['code'] = 1047,
		['name'] = TEXT('朝阳'),
		['province_code'] = 106,
	},
	[48] = {
		['code'] = 1048,
		['name'] = TEXT('葫芦岛'),
		['province_code'] = 106,
	},
	[49] = {
		['code'] = 1049,
		['name'] = TEXT('长春'),
		['province_code'] = 107,
	},
	[50] = {
		['code'] = 1050,
		['name'] = TEXT('吉林'),
		['province_code'] = 107,
	},
	[51] = {
		['code'] = 1051,
		['name'] = TEXT('西平'),
		['province_code'] = 107,
	},
	[52] = {
		['code'] = 1052,
		['name'] = TEXT('辽源'),
		['province_code'] = 107,
	},
	[53] = {
		['code'] = 1053,
		['name'] = TEXT('通化'),
		['province_code'] = 107,
	},
	[54] = {
		['code'] = 1054,
		['name'] = TEXT('白山'),
		['province_code'] = 107,
	},
	[55] = {
		['code'] = 1055,
		['name'] = TEXT('松原'),
		['province_code'] = 107,
	},
	[56] = {
		['code'] = 1056,
		['name'] = TEXT('白城'),
		['province_code'] = 107,
	},
	[57] = {
		['code'] = 1057,
		['name'] = TEXT('延边'),
		['province_code'] = 107,
	},
	[58] = {
		['code'] = 1058,
		['name'] = TEXT('哈尔滨'),
		['province_code'] = 108,
	},
	[59] = {
		['code'] = 1059,
		['name'] = TEXT('齐齐哈尔'),
		['province_code'] = 108,
	},
	[60] = {
		['code'] = 1060,
		['name'] = TEXT('鸡西'),
		['province_code'] = 108,
	},
	[61] = {
		['code'] = 1061,
		['name'] = TEXT('鹤岗'),
		['province_code'] = 108,
	},
	[62] = {
		['code'] = 1062,
		['name'] = TEXT('双鸭山'),
		['province_code'] = 108,
	},
	[63] = {
		['code'] = 1063,
		['name'] = TEXT('大庆'),
		['province_code'] = 108,
	},
	[64] = {
		['code'] = 1064,
		['name'] = TEXT('伊春'),
		['province_code'] = 108,
	},
	[65] = {
		['code'] = 1065,
		['name'] = TEXT('佳木斯'),
		['province_code'] = 108,
	},
	[66] = {
		['code'] = 1066,
		['name'] = TEXT('七台河'),
		['province_code'] = 108,
	},
	[67] = {
		['code'] = 1067,
		['name'] = TEXT('牡丹江'),
		['province_code'] = 108,
	},
	[68] = {
		['code'] = 1068,
		['name'] = TEXT('黑河'),
		['province_code'] = 108,
	},
	[69] = {
		['code'] = 1069,
		['name'] = TEXT('绥化'),
		['province_code'] = 108,
	},
	[70] = {
		['code'] = 1070,
		['name'] = TEXT('大兴安岭'),
		['province_code'] = 108,
	},
	[71] = {
		['code'] = 1071,
		['name'] = TEXT('南京'),
		['province_code'] = 110,
	},
	[72] = {
		['code'] = 1072,
		['name'] = TEXT('无锡'),
		['province_code'] = 110,
	},
	[73] = {
		['code'] = 1073,
		['name'] = TEXT('徐州'),
		['province_code'] = 110,
	},
	[74] = {
		['code'] = 1074,
		['name'] = TEXT('常州'),
		['province_code'] = 110,
	},
	[75] = {
		['code'] = 1075,
		['name'] = TEXT('苏州'),
		['province_code'] = 110,
	},
	[76] = {
		['code'] = 1076,
		['name'] = TEXT('南通'),
		['province_code'] = 110,
	},
	[77] = {
		['code'] = 1077,
		['name'] = TEXT('连云港'),
		['province_code'] = 110,
	},
	[78] = {
		['code'] = 1078,
		['name'] = TEXT('淮安'),
		['province_code'] = 110,
	},
	[79] = {
		['code'] = 1079,
		['name'] = TEXT('盐城'),
		['province_code'] = 110,
	},
	[80] = {
		['code'] = 1080,
		['name'] = TEXT('扬州'),
		['province_code'] = 110,
	},
	[81] = {
		['code'] = 1081,
		['name'] = TEXT('镇江'),
		['province_code'] = 110,
	},
	[82] = {
		['code'] = 1082,
		['name'] = TEXT('泰州'),
		['province_code'] = 110,
	},
	[83] = {
		['code'] = 1083,
		['name'] = TEXT('宿迁'),
		['province_code'] = 110,
	},
	[84] = {
		['code'] = 1084,
		['name'] = TEXT('杭州'),
		['province_code'] = 111,
	},
	[85] = {
		['code'] = 1085,
		['name'] = TEXT('宁波'),
		['province_code'] = 111,
	},
	[86] = {
		['code'] = 1086,
		['name'] = TEXT('温州'),
		['province_code'] = 111,
	},
	[87] = {
		['code'] = 1087,
		['name'] = TEXT('嘉兴'),
		['province_code'] = 111,
	},
	[88] = {
		['code'] = 1088,
		['name'] = TEXT('湖州'),
		['province_code'] = 111,
	},
	[89] = {
		['code'] = 1089,
		['name'] = TEXT('绍兴'),
		['province_code'] = 111,
	},
	[90] = {
		['code'] = 1090,
		['name'] = TEXT('金华'),
		['province_code'] = 111,
	},
	[91] = {
		['code'] = 1091,
		['name'] = TEXT('衢州'),
		['province_code'] = 111,
	},
	[92] = {
		['code'] = 1092,
		['name'] = TEXT('舟山'),
		['province_code'] = 111,
	},
	[93] = {
		['code'] = 1093,
		['name'] = TEXT('台州'),
		['province_code'] = 111,
	},
	[94] = {
		['code'] = 1094,
		['name'] = TEXT('丽水'),
		['province_code'] = 111,
	},
	[95] = {
		['code'] = 1095,
		['name'] = TEXT('合肥'),
		['province_code'] = 112,
	},
	[96] = {
		['code'] = 1096,
		['name'] = TEXT('芜湖'),
		['province_code'] = 112,
	},
	[97] = {
		['code'] = 1097,
		['name'] = TEXT('蚌埠'),
		['province_code'] = 112,
	},
	[98] = {
		['code'] = 1098,
		['name'] = TEXT('淮南'),
		['province_code'] = 112,
	},
	[99] = {
		['code'] = 1099,
		['name'] = TEXT('马鞍山'),
		['province_code'] = 112,
	},
	[100] = {
		['code'] = 1100,
		['name'] = TEXT('淮北'),
		['province_code'] = 112,
	},
	[101] = {
		['code'] = 1101,
		['name'] = TEXT('铜陵'),
		['province_code'] = 112,
	},
	[102] = {
		['code'] = 1102,
		['name'] = TEXT('安庆'),
		['province_code'] = 112,
	},
	[103] = {
		['code'] = 1103,
		['name'] = TEXT('黄山'),
		['province_code'] = 112,
	},
	[104] = {
		['code'] = 1104,
		['name'] = TEXT('滁州'),
		['province_code'] = 112,
	},
	[105] = {
		['code'] = 1105,
		['name'] = TEXT('阜阳'),
		['province_code'] = 112,
	},
	[106] = {
		['code'] = 1106,
		['name'] = TEXT('宿州'),
		['province_code'] = 112,
	},
	[107] = {
		['code'] = 1107,
		['name'] = TEXT('巢湖'),
		['province_code'] = 112,
	},
	[108] = {
		['code'] = 1108,
		['name'] = TEXT('六安'),
		['province_code'] = 112,
	},
	[109] = {
		['code'] = 1109,
		['name'] = TEXT('亳州'),
		['province_code'] = 112,
	},
	[110] = {
		['code'] = 1110,
		['name'] = TEXT('池州'),
		['province_code'] = 112,
	},
	[111] = {
		['code'] = 1111,
		['name'] = TEXT('宣城'),
		['province_code'] = 112,
	},
	[112] = {
		['code'] = 1112,
		['name'] = TEXT('福州'),
		['province_code'] = 113,
	},
	[113] = {
		['code'] = 1113,
		['name'] = TEXT('厦门'),
		['province_code'] = 113,
	},
	[114] = {
		['code'] = 1114,
		['name'] = TEXT('莆田'),
		['province_code'] = 113,
	},
	[115] = {
		['code'] = 1115,
		['name'] = TEXT('三明'),
		['province_code'] = 113,
	},
	[116] = {
		['code'] = 1116,
		['name'] = TEXT('泉州'),
		['province_code'] = 113,
	},
	[117] = {
		['code'] = 1117,
		['name'] = TEXT('漳州'),
		['province_code'] = 113,
	},
	[118] = {
		['code'] = 1118,
		['name'] = TEXT('南平'),
		['province_code'] = 113,
	},
	[119] = {
		['code'] = 1119,
		['name'] = TEXT('龙岩'),
		['province_code'] = 113,
	},
	[120] = {
		['code'] = 1120,
		['name'] = TEXT('宁德'),
		['province_code'] = 113,
	},
	[121] = {
		['code'] = 1121,
		['name'] = TEXT('南昌'),
		['province_code'] = 113,
	},
	[122] = {
		['code'] = 1122,
		['name'] = TEXT('景德镇'),
		['province_code'] = 114,
	},
	[123] = {
		['code'] = 1123,
		['name'] = TEXT('萍乡'),
		['province_code'] = 114,
	},
	[124] = {
		['code'] = 1124,
		['name'] = TEXT('九江'),
		['province_code'] = 114,
	},
	[125] = {
		['code'] = 1125,
		['name'] = TEXT('新余'),
		['province_code'] = 114,
	},
	[126] = {
		['code'] = 1126,
		['name'] = TEXT('鹰潭'),
		['province_code'] = 114,
	},
	[127] = {
		['code'] = 1127,
		['name'] = TEXT('赣州'),
		['province_code'] = 114,
	},
	[128] = {
		['code'] = 1128,
		['name'] = TEXT('吉安'),
		['province_code'] = 114,
	},
	[129] = {
		['code'] = 1129,
		['name'] = TEXT('宜春'),
		['province_code'] = 114,
	},
	[130] = {
		['code'] = 1130,
		['name'] = TEXT('抚州'),
		['province_code'] = 114,
	},
	[131] = {
		['code'] = 1131,
		['name'] = TEXT('上饶'),
		['province_code'] = 114,
	},
	[132] = {
		['code'] = 1132,
		['name'] = TEXT('济南'),
		['province_code'] = 115,
	},
	[133] = {
		['code'] = 1133,
		['name'] = TEXT('青岛'),
		['province_code'] = 115,
	},
	[134] = {
		['code'] = 1134,
		['name'] = TEXT('淄博'),
		['province_code'] = 115,
	},
	[135] = {
		['code'] = 1135,
		['name'] = TEXT('枣庄'),
		['province_code'] = 115,
	},
	[136] = {
		['code'] = 1136,
		['name'] = TEXT('东营'),
		['province_code'] = 115,
	},
	[137] = {
		['code'] = 1137,
		['name'] = TEXT('烟台'),
		['province_code'] = 115,
	},
	[138] = {
		['code'] = 1138,
		['name'] = TEXT('潍坊'),
		['province_code'] = 115,
	},
	[139] = {
		['code'] = 1139,
		['name'] = TEXT('济宁'),
		['province_code'] = 115,
	},
	[140] = {
		['code'] = 1140,
		['name'] = TEXT('泰安'),
		['province_code'] = 115,
	},
	[141] = {
		['code'] = 1141,
		['name'] = TEXT('威海'),
		['province_code'] = 115,
	},
	[142] = {
		['code'] = 1142,
		['name'] = TEXT('日照'),
		['province_code'] = 115,
	},
	[143] = {
		['code'] = 1143,
		['name'] = TEXT('莱芜'),
		['province_code'] = 115,
	},
	[144] = {
		['code'] = 1144,
		['name'] = TEXT('临沂'),
		['province_code'] = 115,
	},
	[145] = {
		['code'] = 1145,
		['name'] = TEXT('德州'),
		['province_code'] = 115,
	},
	[146] = {
		['code'] = 1146,
		['name'] = TEXT('聊城'),
		['province_code'] = 115,
	},
	[147] = {
		['code'] = 1147,
		['name'] = TEXT('滨州'),
		['province_code'] = 115,
	},
	[148] = {
		['code'] = 1148,
		['name'] = TEXT('菏泽'),
		['province_code'] = 115,
	},
	[149] = {
		['code'] = 1149,
		['name'] = TEXT('郑州'),
		['province_code'] = 116,
	},
	[150] = {
		['code'] = 1150,
		['name'] = TEXT('开封'),
		['province_code'] = 116,
	},
	[151] = {
		['code'] = 1151,
		['name'] = TEXT('洛阳'),
		['province_code'] = 116,
	},
	[152] = {
		['code'] = 1152,
		['name'] = TEXT('平顶山'),
		['province_code'] = 116,
	},
	[153] = {
		['code'] = 1153,
		['name'] = TEXT('安阳'),
		['province_code'] = 116,
	},
	[154] = {
		['code'] = 1154,
		['name'] = TEXT('鹤壁'),
		['province_code'] = 116,
	},
	[155] = {
		['code'] = 1155,
		['name'] = TEXT('新乡'),
		['province_code'] = 116,
	},
	[156] = {
		['code'] = 1156,
		['name'] = TEXT('焦作'),
		['province_code'] = 116,
	},
	[157] = {
		['code'] = 1157,
		['name'] = TEXT('濮阳'),
		['province_code'] = 116,
	},
	[158] = {
		['code'] = 1158,
		['name'] = TEXT('许昌'),
		['province_code'] = 116,
	},
	[159] = {
		['code'] = 1159,
		['name'] = TEXT('漯河'),
		['province_code'] = 116,
	},
	[160] = {
		['code'] = 1160,
		['name'] = TEXT('三门峡'),
		['province_code'] = 116,
	},
	[161] = {
		['code'] = 1161,
		['name'] = TEXT('南阳'),
		['province_code'] = 116,
	},
	[162] = {
		['code'] = 1162,
		['name'] = TEXT('商丘'),
		['province_code'] = 116,
	},
	[163] = {
		['code'] = 1163,
		['name'] = TEXT('信阳'),
		['province_code'] = 116,
	},
	[164] = {
		['code'] = 1164,
		['name'] = TEXT('周口'),
		['province_code'] = 116,
	},
	[165] = {
		['code'] = 1165,
		['name'] = TEXT('驻马店'),
		['province_code'] = 116,
	},
	[166] = {
		['code'] = 1166,
		['name'] = TEXT('武汉'),
		['province_code'] = 117,
	},
	[167] = {
		['code'] = 1167,
		['name'] = TEXT('黄石'),
		['province_code'] = 117,
	},
	[168] = {
		['code'] = 1168,
		['name'] = TEXT('十堰'),
		['province_code'] = 117,
	},
	[169] = {
		['code'] = 1169,
		['name'] = TEXT('宜昌'),
		['province_code'] = 117,
	},
	[170] = {
		['code'] = 1170,
		['name'] = TEXT('襄樊'),
		['province_code'] = 117,
	},
	[171] = {
		['code'] = 1171,
		['name'] = TEXT('鄂州'),
		['province_code'] = 117,
	},
	[172] = {
		['code'] = 1172,
		['name'] = TEXT('荆门'),
		['province_code'] = 117,
	},
	[173] = {
		['code'] = 1173,
		['name'] = TEXT('孝感'),
		['province_code'] = 117,
	},
	[174] = {
		['code'] = 1174,
		['name'] = TEXT('荆州'),
		['province_code'] = 117,
	},
	[175] = {
		['code'] = 1175,
		['name'] = TEXT('黄冈'),
		['province_code'] = 117,
	},
	[176] = {
		['code'] = 1176,
		['name'] = TEXT('咸宁'),
		['province_code'] = 117,
	},
	[177] = {
		['code'] = 1177,
		['name'] = TEXT('随州'),
		['province_code'] = 117,
	},
	[178] = {
		['code'] = 1178,
		['name'] = TEXT('恩施'),
		['province_code'] = 117,
	},
	[179] = {
		['code'] = 1179,
		['name'] = TEXT('仙桃'),
		['province_code'] = 117,
	},
	[180] = {
		['code'] = 1180,
		['name'] = TEXT('潜江'),
		['province_code'] = 117,
	},
	[181] = {
		['code'] = 1181,
		['name'] = TEXT('天门'),
		['province_code'] = 117,
	},
	[182] = {
		['code'] = 1182,
		['name'] = TEXT('神农架'),
		['province_code'] = 117,
	},
	[183] = {
		['code'] = 1183,
		['name'] = TEXT('长沙'),
		['province_code'] = 118,
	},
	[184] = {
		['code'] = 1184,
		['name'] = TEXT('株洲'),
		['province_code'] = 118,
	},
	[185] = {
		['code'] = 1185,
		['name'] = TEXT('湘潭'),
		['province_code'] = 118,
	},
	[186] = {
		['code'] = 1186,
		['name'] = TEXT('衡阳'),
		['province_code'] = 118,
	},
	[187] = {
		['code'] = 1187,
		['name'] = TEXT('邵阳'),
		['province_code'] = 118,
	},
	[188] = {
		['code'] = 1188,
		['name'] = TEXT('岳阳'),
		['province_code'] = 118,
	},
	[189] = {
		['code'] = 1189,
		['name'] = TEXT('常德'),
		['province_code'] = 118,
	},
	[190] = {
		['code'] = 1190,
		['name'] = TEXT('张家界'),
		['province_code'] = 118,
	},
	[191] = {
		['code'] = 1191,
		['name'] = TEXT('益阳'),
		['province_code'] = 118,
	},
	[192] = {
		['code'] = 1192,
		['name'] = TEXT('郴州'),
		['province_code'] = 118,
	},
	[193] = {
		['code'] = 1193,
		['name'] = TEXT('永州'),
		['province_code'] = 118,
	},
	[194] = {
		['code'] = 1194,
		['name'] = TEXT('怀化'),
		['province_code'] = 118,
	},
	[195] = {
		['code'] = 1195,
		['name'] = TEXT('娄底'),
		['province_code'] = 118,
	},
	[196] = {
		['code'] = 1196,
		['name'] = TEXT('湘西'),
		['province_code'] = 118,
	},
	[197] = {
		['code'] = 1197,
		['name'] = TEXT('广州'),
		['province_code'] = 119,
	},
	[198] = {
		['code'] = 1198,
		['name'] = TEXT('韶关'),
		['province_code'] = 119,
	},
	[199] = {
		['code'] = 1199,
		['name'] = TEXT('深圳'),
		['province_code'] = 119,
	},
	[200] = {
		['code'] = 1200,
		['name'] = TEXT('珠海'),
		['province_code'] = 119,
	},
	[201] = {
		['code'] = 1201,
		['name'] = TEXT('汕头'),
		['province_code'] = 119,
	},
	[202] = {
		['code'] = 1202,
		['name'] = TEXT('佛山'),
		['province_code'] = 119,
	},
	[203] = {
		['code'] = 1203,
		['name'] = TEXT('江门'),
		['province_code'] = 119,
	},
	[204] = {
		['code'] = 1204,
		['name'] = TEXT('湛江'),
		['province_code'] = 119,
	},
	[205] = {
		['code'] = 1205,
		['name'] = TEXT('茂名'),
		['province_code'] = 119,
	},
	[206] = {
		['code'] = 1206,
		['name'] = TEXT('肇庆'),
		['province_code'] = 119,
	},
	[207] = {
		['code'] = 1207,
		['name'] = TEXT('惠州'),
		['province_code'] = 119,
	},
	[208] = {
		['code'] = 1208,
		['name'] = TEXT('梅州'),
		['province_code'] = 119,
	},
	[209] = {
		['code'] = 1209,
		['name'] = TEXT('汕尾'),
		['province_code'] = 119,
	},
	[210] = {
		['code'] = 1210,
		['name'] = TEXT('河源'),
		['province_code'] = 119,
	},
	[211] = {
		['code'] = 1211,
		['name'] = TEXT('阳江'),
		['province_code'] = 119,
	},
	[212] = {
		['code'] = 1212,
		['name'] = TEXT('清远'),
		['province_code'] = 119,
	},
	[213] = {
		['code'] = 1213,
		['name'] = TEXT('东莞'),
		['province_code'] = 119,
	},
	[214] = {
		['code'] = 1214,
		['name'] = TEXT('中山'),
		['province_code'] = 119,
	},
	[215] = {
		['code'] = 1215,
		['name'] = TEXT('潮州'),
		['province_code'] = 119,
	},
	[216] = {
		['code'] = 1216,
		['name'] = TEXT('揭阳'),
		['province_code'] = 119,
	},
	[217] = {
		['code'] = 1217,
		['name'] = TEXT('云浮'),
		['province_code'] = 119,
	},
	[218] = {
		['code'] = 1218,
		['name'] = TEXT('南宁'),
		['province_code'] = 120,
	},
	[219] = {
		['code'] = 1219,
		['name'] = TEXT('柳州'),
		['province_code'] = 120,
	},
	[220] = {
		['code'] = 1220,
		['name'] = TEXT('桂林'),
		['province_code'] = 120,
	},
	[221] = {
		['code'] = 1221,
		['name'] = TEXT('梧州'),
		['province_code'] = 120,
	},
	[222] = {
		['code'] = 1222,
		['name'] = TEXT('北海'),
		['province_code'] = 120,
	},
	[223] = {
		['code'] = 1223,
		['name'] = TEXT('防城港'),
		['province_code'] = 120,
	},
	[224] = {
		['code'] = 1224,
		['name'] = TEXT('钦州'),
		['province_code'] = 120,
	},
	[225] = {
		['code'] = 1225,
		['name'] = TEXT('贵港'),
		['province_code'] = 120,
	},
	[226] = {
		['code'] = 1226,
		['name'] = TEXT('玉林'),
		['province_code'] = 120,
	},
	[227] = {
		['code'] = 1227,
		['name'] = TEXT('百色'),
		['province_code'] = 120,
	},
	[228] = {
		['code'] = 1228,
		['name'] = TEXT('贺州'),
		['province_code'] = 120,
	},
	[229] = {
		['code'] = 1229,
		['name'] = TEXT('河池'),
		['province_code'] = 120,
	},
	[230] = {
		['code'] = 1230,
		['name'] = TEXT('来宾'),
		['province_code'] = 120,
	},
	[231] = {
		['code'] = 1231,
		['name'] = TEXT('崇左'),
		['province_code'] = 120,
	},
	[232] = {
		['code'] = 1232,
		['name'] = TEXT('海口'),
		['province_code'] = 121,
	},
	[233] = {
		['code'] = 1233,
		['name'] = TEXT('三亚'),
		['province_code'] = 121,
	},
	[234] = {
		['code'] = 1234,
		['name'] = TEXT('五指山'),
		['province_code'] = 121,
	},
	[235] = {
		['code'] = 1235,
		['name'] = TEXT('琼海'),
		['province_code'] = 121,
	},
	[236] = {
		['code'] = 1236,
		['name'] = TEXT('儋州'),
		['province_code'] = 121,
	},
	[237] = {
		['code'] = 1237,
		['name'] = TEXT('琼山'),
		['province_code'] = 121,
	},
	[238] = {
		['code'] = 1238,
		['name'] = TEXT('文昌'),
		['province_code'] = 121,
	},
	[239] = {
		['code'] = 1239,
		['name'] = TEXT('万宁'),
		['province_code'] = 121,
	},
	[240] = {
		['code'] = 1240,
		['name'] = TEXT('东方'),
		['province_code'] = 121,
	},
	[241] = {
		['code'] = 1241,
		['name'] = TEXT('定安'),
		['province_code'] = 121,
	},
	[242] = {
		['code'] = 1242,
		['name'] = TEXT('屯昌'),
		['province_code'] = 121,
	},
	[243] = {
		['code'] = 1243,
		['name'] = TEXT('澄迈'),
		['province_code'] = 121,
	},
	[244] = {
		['code'] = 1244,
		['name'] = TEXT('临高'),
		['province_code'] = 121,
	},
	[245] = {
		['code'] = 1245,
		['name'] = TEXT('三沙'),
		['province_code'] = 121,
	},
	[246] = {
		['code'] = 1246,
		['name'] = TEXT('成都'),
		['province_code'] = 123,
	},
	[247] = {
		['code'] = 1247,
		['name'] = TEXT('自贡'),
		['province_code'] = 123,
	},
	[248] = {
		['code'] = 1248,
		['name'] = TEXT('攀枝花'),
		['province_code'] = 123,
	},
	[249] = {
		['code'] = 1249,
		['name'] = TEXT('泸州'),
		['province_code'] = 123,
	},
	[250] = {
		['code'] = 1250,
		['name'] = TEXT('德阳'),
		['province_code'] = 123,
	},
	[251] = {
		['code'] = 1251,
		['name'] = TEXT('绵阳'),
		['province_code'] = 123,
	},
	[252] = {
		['code'] = 1252,
		['name'] = TEXT('广元'),
		['province_code'] = 123,
	},
	[253] = {
		['code'] = 1253,
		['name'] = TEXT('遂宁'),
		['province_code'] = 123,
	},
	[254] = {
		['code'] = 1254,
		['name'] = TEXT('内江'),
		['province_code'] = 123,
	},
	[255] = {
		['code'] = 1255,
		['name'] = TEXT('乐山'),
		['province_code'] = 123,
	},
	[256] = {
		['code'] = 1256,
		['name'] = TEXT('南充'),
		['province_code'] = 123,
	},
	[257] = {
		['code'] = 1257,
		['name'] = TEXT('眉山'),
		['province_code'] = 123,
	},
	[258] = {
		['code'] = 1258,
		['name'] = TEXT('宜宾'),
		['province_code'] = 123,
	},
	[259] = {
		['code'] = 1259,
		['name'] = TEXT('广安'),
		['province_code'] = 123,
	},
	[260] = {
		['code'] = 1260,
		['name'] = TEXT('达州'),
		['province_code'] = 123,
	},
	[261] = {
		['code'] = 1261,
		['name'] = TEXT('雅安'),
		['province_code'] = 123,
	},
	[262] = {
		['code'] = 1262,
		['name'] = TEXT('巴中'),
		['province_code'] = 123,
	},
	[263] = {
		['code'] = 1263,
		['name'] = TEXT('资阳'),
		['province_code'] = 123,
	},
	[264] = {
		['code'] = 1264,
		['name'] = TEXT('阿坝'),
		['province_code'] = 123,
	},
	[265] = {
		['code'] = 1265,
		['name'] = TEXT('甘孜'),
		['province_code'] = 123,
	},
	[266] = {
		['code'] = 1266,
		['name'] = TEXT('凉山'),
		['province_code'] = 123,
	},
	[267] = {
		['code'] = 1267,
		['name'] = TEXT('贵阳'),
		['province_code'] = 124,
	},
	[268] = {
		['code'] = 1268,
		['name'] = TEXT('六盘水'),
		['province_code'] = 124,
	},
	[269] = {
		['code'] = 1269,
		['name'] = TEXT('遵义'),
		['province_code'] = 124,
	},
	[270] = {
		['code'] = 1270,
		['name'] = TEXT('安顺'),
		['province_code'] = 124,
	},
	[271] = {
		['code'] = 1271,
		['name'] = TEXT('铜仁'),
		['province_code'] = 124,
	},
	[272] = {
		['code'] = 1272,
		['name'] = TEXT('黔西南'),
		['province_code'] = 124,
	},
	[273] = {
		['code'] = 1273,
		['name'] = TEXT('黔东南'),
		['province_code'] = 124,
	},
	[274] = {
		['code'] = 1274,
		['name'] = TEXT('黔南'),
		['province_code'] = 124,
	},
	[275] = {
		['code'] = 1275,
		['name'] = TEXT('毕节'),
		['province_code'] = 124,
	},
	[276] = {
		['code'] = 1276,
		['name'] = TEXT('昆明'),
		['province_code'] = 125,
	},
	[277] = {
		['code'] = 1277,
		['name'] = TEXT('曲靖'),
		['province_code'] = 125,
	},
	[278] = {
		['code'] = 1278,
		['name'] = TEXT('玉溪'),
		['province_code'] = 125,
	},
	[279] = {
		['code'] = 1279,
		['name'] = TEXT('保山'),
		['province_code'] = 125,
	},
	[280] = {
		['code'] = 1280,
		['name'] = TEXT('昭通'),
		['province_code'] = 125,
	},
	[281] = {
		['code'] = 1281,
		['name'] = TEXT('丽江'),
		['province_code'] = 125,
	},
	[282] = {
		['code'] = 1282,
		['name'] = TEXT('思茅'),
		['province_code'] = 125,
	},
	[283] = {
		['code'] = 1283,
		['name'] = TEXT('临沧'),
		['province_code'] = 125,
	},
	[284] = {
		['code'] = 1284,
		['name'] = TEXT('楚雄'),
		['province_code'] = 125,
	},
	[285] = {
		['code'] = 1285,
		['name'] = TEXT('红河'),
		['province_code'] = 125,
	},
	[286] = {
		['code'] = 1286,
		['name'] = TEXT('文山'),
		['province_code'] = 125,
	},
	[287] = {
		['code'] = 1287,
		['name'] = TEXT('西双版纳'),
		['province_code'] = 125,
	},
	[288] = {
		['code'] = 1288,
		['name'] = TEXT('大理'),
		['province_code'] = 125,
	},
	[289] = {
		['code'] = 1289,
		['name'] = TEXT('德宏'),
		['province_code'] = 125,
	},
	[290] = {
		['code'] = 1290,
		['name'] = TEXT('怒江'),
		['province_code'] = 125,
	},
	[291] = {
		['code'] = 1291,
		['name'] = TEXT('迪庆'),
		['province_code'] = 125,
	},
	[292] = {
		['code'] = 1292,
		['name'] = TEXT('拉萨'),
		['province_code'] = 126,
	},
	[293] = {
		['code'] = 1293,
		['name'] = TEXT('昌都'),
		['province_code'] = 126,
	},
	[294] = {
		['code'] = 1294,
		['name'] = TEXT('山南'),
		['province_code'] = 126,
	},
	[295] = {
		['code'] = 1295,
		['name'] = TEXT('日喀则'),
		['province_code'] = 126,
	},
	[296] = {
		['code'] = 1296,
		['name'] = TEXT('那曲'),
		['province_code'] = 126,
	},
	[297] = {
		['code'] = 1297,
		['name'] = TEXT('阿里'),
		['province_code'] = 126,
	},
	[298] = {
		['code'] = 1298,
		['name'] = TEXT('林芝'),
		['province_code'] = 126,
	},
	[299] = {
		['code'] = 1299,
		['name'] = TEXT('西安'),
		['province_code'] = 127,
	},
	[300] = {
		['code'] = 1300,
		['name'] = TEXT('铜川'),
		['province_code'] = 127,
	},
	[301] = {
		['code'] = 1301,
		['name'] = TEXT('宝鸡'),
		['province_code'] = 127,
	},
	[302] = {
		['code'] = 1302,
		['name'] = TEXT('咸阳'),
		['province_code'] = 127,
	},
	[303] = {
		['code'] = 1303,
		['name'] = TEXT('渭南'),
		['province_code'] = 127,
	},
	[304] = {
		['code'] = 1304,
		['name'] = TEXT('延安'),
		['province_code'] = 127,
	},
	[305] = {
		['code'] = 1305,
		['name'] = TEXT('汉中'),
		['province_code'] = 127,
	},
	[306] = {
		['code'] = 1306,
		['name'] = TEXT('榆林'),
		['province_code'] = 127,
	},
	[307] = {
		['code'] = 1307,
		['name'] = TEXT('安康'),
		['province_code'] = 127,
	},
	[308] = {
		['code'] = 1308,
		['name'] = TEXT('商洛'),
		['province_code'] = 127,
	},
	[309] = {
		['code'] = 1309,
		['name'] = TEXT('兰州'),
		['province_code'] = 128,
	},
	[310] = {
		['code'] = 1310,
		['name'] = TEXT('嘉峪关'),
		['province_code'] = 128,
	},
	[311] = {
		['code'] = 1311,
		['name'] = TEXT('金昌'),
		['province_code'] = 128,
	},
	[312] = {
		['code'] = 1312,
		['name'] = TEXT('白银'),
		['province_code'] = 128,
	},
	[313] = {
		['code'] = 1313,
		['name'] = TEXT('天水'),
		['province_code'] = 128,
	},
	[314] = {
		['code'] = 1314,
		['name'] = TEXT('武威'),
		['province_code'] = 128,
	},
	[315] = {
		['code'] = 1315,
		['name'] = TEXT('张掖'),
		['province_code'] = 128,
	},
	[316] = {
		['code'] = 1316,
		['name'] = TEXT('平凉'),
		['province_code'] = 128,
	},
	[317] = {
		['code'] = 1317,
		['name'] = TEXT('酒泉'),
		['province_code'] = 128,
	},
	[318] = {
		['code'] = 1318,
		['name'] = TEXT('庆阳'),
		['province_code'] = 128,
	},
	[319] = {
		['code'] = 1319,
		['name'] = TEXT('定西'),
		['province_code'] = 128,
	},
	[320] = {
		['code'] = 1320,
		['name'] = TEXT('陇南'),
		['province_code'] = 128,
	},
	[321] = {
		['code'] = 1321,
		['name'] = TEXT('临夏'),
		['province_code'] = 128,
	},
	[322] = {
		['code'] = 1322,
		['name'] = TEXT('甘南'),
		['province_code'] = 128,
	},
	[323] = {
		['code'] = 1323,
		['name'] = TEXT('西宁'),
		['province_code'] = 129,
	},
	[324] = {
		['code'] = 1324,
		['name'] = TEXT('海东'),
		['province_code'] = 129,
	},
	[325] = {
		['code'] = 1325,
		['name'] = TEXT('海北'),
		['province_code'] = 129,
	},
	[326] = {
		['code'] = 1326,
		['name'] = TEXT('黄南'),
		['province_code'] = 129,
	},
	[327] = {
		['code'] = 1327,
		['name'] = TEXT('海南'),
		['province_code'] = 129,
	},
	[328] = {
		['code'] = 1328,
		['name'] = TEXT('果洛'),
		['province_code'] = 129,
	},
	[329] = {
		['code'] = 1329,
		['name'] = TEXT('玉树'),
		['province_code'] = 129,
	},
	[330] = {
		['code'] = 1330,
		['name'] = TEXT('海西'),
		['province_code'] = 129,
	},
	[331] = {
		['code'] = 1331,
		['name'] = TEXT('银川'),
		['province_code'] = 130,
	},
	[332] = {
		['code'] = 1332,
		['name'] = TEXT('石嘴山'),
		['province_code'] = 130,
	},
	[333] = {
		['code'] = 1333,
		['name'] = TEXT('吴中'),
		['province_code'] = 130,
	},
	[334] = {
		['code'] = 1334,
		['name'] = TEXT('固原'),
		['province_code'] = 130,
	},
	[335] = {
		['code'] = 1335,
		['name'] = TEXT('中卫'),
		['province_code'] = 130,
	},
	[336] = {
		['code'] = 1336,
		['name'] = TEXT('乌鲁木齐'),
		['province_code'] = 131,
	},
	[337] = {
		['code'] = 1337,
		['name'] = TEXT('克拉玛依'),
		['province_code'] = 131,
	},
	[338] = {
		['code'] = 1338,
		['name'] = TEXT('吐鲁番'),
		['province_code'] = 131,
	},
	[339] = {
		['code'] = 1339,
		['name'] = TEXT('哈密'),
		['province_code'] = 131,
	},
	[340] = {
		['code'] = 1340,
		['name'] = TEXT('昌吉'),
		['province_code'] = 131,
	},
	[341] = {
		['code'] = 1341,
		['name'] = TEXT('博尔塔拉'),
		['province_code'] = 131,
	},
	[342] = {
		['code'] = 1342,
		['name'] = TEXT('巴音郭楞'),
		['province_code'] = 131,
	},
	[343] = {
		['code'] = 1343,
		['name'] = TEXT('阿克苏'),
		['province_code'] = 131,
	},
	[344] = {
		['code'] = 1344,
		['name'] = TEXT('克孜勒'),
		['province_code'] = 131,
	},
	[345] = {
		['code'] = 1345,
		['name'] = TEXT('喀什'),
		['province_code'] = 131,
	},
	[346] = {
		['code'] = 1346,
		['name'] = TEXT('和田'),
		['province_code'] = 131,
	},
	[347] = {
		['code'] = 1347,
		['name'] = TEXT('伊犁'),
		['province_code'] = 131,
	},
	[348] = {
		['code'] = 1348,
		['name'] = TEXT('塔城'),
		['province_code'] = 131,
	},
	[349] = {
		['code'] = 1349,
		['name'] = TEXT('阿勒泰'),
		['province_code'] = 131,
	},
	[350] = {
		['code'] = 1350,
		['name'] = TEXT('石河子'),
		['province_code'] = 131,
	},
	[351] = {
		['code'] = 1351,
		['name'] = TEXT('阿拉尔布'),
		['province_code'] = 131,
	},
	[352] = {
		['code'] = 1352,
		['name'] = TEXT('图木舒克'),
		['province_code'] = 131,
	},
	[353] = {
		['code'] = 1353,
		['name'] = TEXT('五家渠'),
		['province_code'] = 131,
	},
	[354] = {
		['code'] = 1354,
		['name'] = TEXT('台北'),
		['province_code'] = 132,
	},
	[355] = {
		['code'] = 1355,
		['name'] = TEXT('高雄'),
		['province_code'] = 132,
	},
	[356] = {
		['code'] = 1356,
		['name'] = TEXT('基隆'),
		['province_code'] = 132,
	},
	[357] = {
		['code'] = 1357,
		['name'] = TEXT('台中'),
		['province_code'] = 132,
	},
	[358] = {
		['code'] = 1358,
		['name'] = TEXT('台南'),
		['province_code'] = 132,
	},
	[359] = {
		['code'] = 1359,
		['name'] = TEXT('新竹'),
		['province_code'] = 132,
	},
	[360] = {
		['code'] = 1360,
		['name'] = TEXT('嘉义'),
		['province_code'] = 132,
	},
	[361] = {
		['code'] = 1361,
		['name'] = TEXT('金门'),
		['province_code'] = 132,
	},
	[362] = {
		['code'] = 1362,
		['name'] = TEXT('马祖'),
		['province_code'] = 132,
	},
})
