// Generated by xls2ts.py
// DO NOT EDIT!
///<reference path="text.ts" />

module Data {

    export class bonus {

        private static _data = {
            1: {"__id__": 1, "priority": 2, "function": ["turn==3"], "name": Core.StringUtils.TEXT(8301), "total": [1, 2], "weapon": [0, 1], "horse": [0, 1], "material": [0, 1], "forage": [], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, 2], "book_duel": [0, 2] },
			2: {"__id__": 2, "priority": 2, "function": ["turn==4"], "name": Core.StringUtils.TEXT(8302), "total": [1, 3], "weapon": [0, 2], "horse": [0, 2], "material": [0, 2], "forage": [0, 1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, 2], "book_duel": [0, 2] },
			3: {"__id__": 3, "priority": 2, "function": ["turn==5"], "name": Core.StringUtils.TEXT(8303), "total": [2, 4], "weapon": [0, 2], "horse": [0, 2], "material": [0, 2], "forage": [0, 1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, 3], "book_duel": [0, 3] },
			4: {"__id__": 4, "priority": 2, "function": ["turn==6"], "name": Core.StringUtils.TEXT(8304), "total": [2, 5], "weapon": [0, 2], "horse": [0, 2], "material": [0, 2], "forage": [0, 1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, 3], "book_duel": [0, 3] },
			5: {"__id__": 5, "priority": 2, "function": ["turn==7"], "name": Core.StringUtils.TEXT(8305), "total": [3, 6], "weapon": [0, 2], "horse": [0, 2], "material": [0, 2], "forage": [0, 2], "medicine": [], "bandage": [0, 1], "gold": 0, "energy": 0.0, "wine_duel": [1, 4], "book_duel": [1, 4] },
			6: {"__id__": 6, "priority": 2, "function": ["turn==8"], "name": Core.StringUtils.TEXT(8306), "total": [4, 7], "weapon": [0, 3], "horse": [0, 3], "material": [0, 3], "forage": [0, 2], "medicine": [], "bandage": [0, 1], "gold": 0, "energy": 0.0, "wine_duel": [1, 4], "book_duel": [1, 4] },
			7: {"__id__": 7, "priority": 2, "function": ["turn>=9"], "name": Core.StringUtils.TEXT(8307), "total": [5, 8], "weapon": [0, 3], "horse": [0, 3], "material": [0, 3], "forage": [0, 2], "medicine": [], "bandage": [0, 1], "gold": 0, "energy": 0.0, "wine_duel": [2, 5], "book_duel": [2, 5] },
			8: {"__id__": 8, "priority": 2, "function": ["front==9", "win"], "name": Core.StringUtils.TEXT(8308), "total": [2, 5], "weapon": [0, 3], "horse": [0, 3], "material": [0, 3], "forage": [0, 2], "medicine": [], "bandage": [0, 1], "gold": 0, "energy": 0.0, "wine_duel": [0, 3], "book_duel": [0, 3] },
			9: {"__id__": 9, "priority": 1, "function": ["turn>=5", "front==9", "win"], "name": Core.StringUtils.TEXT(8309), "total": [7, 13], "weapon": [0, 3], "horse": [0, 3], "material": [0, 3], "forage": [0, 2], "medicine": [], "bandage": [0, 1], "gold": 300, "energy": 0.0, "wine_duel": [1, 4], "book_duel": [1, 4] },
			10: {"__id__": 10, "priority": 2, "function": ["beturn==3"], "name": Core.StringUtils.TEXT(8310), "total": [-1, -2], "weapon": [0, -1], "horse": [0, -1], "material": [0, -1], "forage": [], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, -2], "book_duel": [0, -2] },
			11: {"__id__": 11, "priority": 2, "function": ["beturn==4"], "name": Core.StringUtils.TEXT(8311), "total": [-1, -3], "weapon": [0, -2], "horse": [0, -2], "material": [0, -2], "forage": [0, -1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [0, -2], "book_duel": [0, -2] },
			12: {"__id__": 12, "priority": 2, "function": ["beturn==5"], "name": Core.StringUtils.TEXT(8312), "total": [-2, -4], "weapon": [0, -2], "horse": [0, -2], "material": [0, -2], "forage": [0, -1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [-0, -3], "book_duel": [-0, -3] },
			13: {"__id__": 13, "priority": 2, "function": ["beturn==6"], "name": Core.StringUtils.TEXT(8313), "total": [-2, -5], "weapon": [0, -2], "horse": [0, -2], "material": [0, -2], "forage": [0, -1], "medicine": [], "bandage": [], "gold": 0, "energy": 0.0, "wine_duel": [-0, -3], "book_duel": [-0, -3] },
			14: {"__id__": 14, "priority": 2, "function": ["beturn==7"], "name": Core.StringUtils.TEXT(8314), "total": [-3, -6], "weapon": [0, -2], "horse": [0, -2], "material": [0, -2], "forage": [0, -2], "medicine": [], "bandage": [0, -1], "gold": 0, "energy": 0.0, "wine_duel": [-1, -4], "book_duel": [-1, -4] },
			15: {"__id__": 15, "priority": 2, "function": ["beturn==8"], "name": Core.StringUtils.TEXT(8315), "total": [-4, -7], "weapon": [0, -3], "horse": [0, -3], "material": [0, -3], "forage": [0, -2], "medicine": [], "bandage": [0, -1], "gold": 0, "energy": 0.0, "wine_duel": [-1, -4], "book_duel": [-1, -4] },
			16: {"__id__": 16, "priority": 2, "function": ["beturn>=9"], "name": Core.StringUtils.TEXT(8316), "total": [-5, -8], "weapon": [0, -3], "horse": [0, -3], "material": [0, -3], "forage": [0, -2], "medicine": [], "bandage": [0, -1], "gold": 0, "energy": 0.0, "wine_duel": [-2, -5], "book_duel": [-2, -5] },
			17: {"__id__": 17, "priority": 2, "function": ["opp==9", "lose"], "name": Core.StringUtils.TEXT(8317), "total": [-2, -5], "weapon": [0, -3], "horse": [0, -3], "material": [0, -3], "forage": [0, -2], "medicine": [], "bandage": [0, -1], "gold": 0, "energy": 0.0, "wine_duel": [-0, -3], "book_duel": [-0, -3] },
			18: {"__id__": 18, "priority": 1, "function": ["beturn>=5", "opp==9", "lose"], "name": Core.StringUtils.TEXT(8318), "total": [-7, -13], "weapon": [0, -3], "horse": [0, -3], "material": [0, -3], "forage": [0, -2], "medicine": [], "bandage": [0, -1], "gold": -300, "energy": 0.0, "wine_duel": [-1, -4], "book_duel": [-1, -4] }
		}

		private static _keys = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];

        public static get(id:number): any {
            return bonus._data[id];
        }

        public static get keys() {
            return bonus._keys
        }
    }
    
}
