// Generated by xls2ts.py
// DO NOT EDIT!
///<reference path="text.ts" />

module Data {

    export class diy {

        private static _data = {
            1: {"__id__": 1, "skill": [1041], "ban": [6, 13, 41], "level": 1, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 26, "wine": 8, "book": 12 },
			2: {"__id__": 2, "skill": [1061, 1062], "ban": [], "level": 1, "min_single": 2, "max_single": 5, "min_total": 10, "max_total": 20, "wine": 12, "book": 8 },
			3: {"__id__": 3, "skill": [1101], "ban": [], "level": 1, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 14, "book": 6 },
			4: {"__id__": 4, "skill": [1151], "ban": [23, 37, 45], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 12, "book": 8 },
			5: {"__id__": 5, "skill": [1270], "ban": [], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 7, "book": 13 },
			6: {"__id__": 6, "skill": [1321], "ban": [1, 26, 32, 44, 54, 59], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 27, "wine": 8, "book": 12 },
			7: {"__id__": 7, "skill": [1341], "ban": [], "level": 1, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 4, "book": 16 },
			8: {"__id__": 8, "skill": [1091], "ban": [], "level": 1, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 4, "book": 16 },
			9: {"__id__": 9, "skill": [1131], "ban": [], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 12, "book": 8 },
			10: {"__id__": 10, "skill": [1115], "ban": [], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 14, "book": 6 },
			11: {"__id__": 11, "skill": [1201], "ban": [], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 15, "book": 5 },
			12: {"__id__": 12, "skill": [1051], "ban": [37, 45], "level": 1, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 10, "book": 10 },
			13: {"__id__": 13, "skill": [1301], "ban": [1, 26, 32, 44, 54, 59], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 27, "wine": 13, "book": 17 },
			14: {"__id__": 14, "skill": [1281], "ban": [], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 24, "book": 6 },
			15: {"__id__": 15, "skill": [1313], "ban": [], "level": 2, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 18, "book": 12 },
			16: {"__id__": 16, "skill": [1392], "ban": [], "level": 2, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 25, "wine": 12, "book": 18 },
			17: {"__id__": 17, "skill": [1211], "ban": [], "level": 2, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 12, "book": 18 },
			18: {"__id__": 18, "skill": [1461], "ban": [], "level": 2, "min_single": 2, "max_single": 6, "min_total": 10, "max_total": 24, "wine": 12, "book": 18 },
			19: {"__id__": 19, "skill": [1011], "ban": [], "level": 2, "min_single": 2, "max_single": 5, "min_total": 10, "max_total": 24, "wine": 9, "book": 21 },
			20: {"__id__": 20, "skill": [1112], "ban": [45], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 19, "book": 11 },
			21: {"__id__": 21, "skill": [1071], "ban": [], "level": 2, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 15, "book": 15 },
			22: {"__id__": 22, "skill": [1132], "ban": [], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 20, "book": 10 },
			23: {"__id__": 23, "skill": [1401], "ban": [4, 37, 24, 45, 60], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 11, "book": 19 },
			24: {"__id__": 24, "skill": [1451], "ban": [23, 37, 45, 60], "level": 2, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 15, "book": 15 },
			25: {"__id__": 25, "skill": [1135], "ban": [], "level": 3, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 25, "wine": 18, "book": 22 },
			26: {"__id__": 26, "skill": [1042], "ban": [6, 13, 41], "level": 3, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 28, "wine": 24, "book": 16 },
			27: {"__id__": 27, "skill": [1411], "ban": [], "level": 3, "min_single": 2, "max_single": 5, "min_total": 10, "max_total": 20, "wine": 8, "book": 32 },
			28: {"__id__": 28, "skill": [1081], "ban": [], "level": 3, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 21, "wine": 14, "book": 26 },
			29: {"__id__": 29, "skill": [1256], "ban": [], "level": 3, "min_single": 4, "max_single": 6, "min_total": 10, "max_total": 24, "wine": 32, "book": 8 },
			30: {"__id__": 30, "skill": [1102], "ban": [], "level": 3, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 20, "book": 20 },
			31: {"__id__": 31, "skill": [1141], "ban": [], "level": 3, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 22, "book": 18 },
			32: {"__id__": 32, "skill": [1191, 1192], "ban": [6, 13, 41], "level": 3, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 13, "book": 27 },
			33: {"__id__": 33, "skill": [1257], "ban": [], "level": 3, "min_single": 4, "max_single": 6, "min_total": 15, "max_total": 24, "wine": 12, "book": 28 },
			34: {"__id__": 34, "skill": [1271], "ban": [], "level": 3, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 26, "wine": 20, "book": 20 },
			35: {"__id__": 35, "skill": [1015], "ban": [], "level": 3, "min_single": 2, "max_single": 6, "min_total": 10, "max_total": 20, "wine": 22, "book": 18 },
			36: {"__id__": 36, "skill": [1831], "ban": [45], "level": 3, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 28, "wine": 35, "book": 5 },
			37: {"__id__": 37, "skill": [1441], "ban": [4, 12, 23, 24, 45, 60], "level": 4, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 32, "wine": 35, "book": 15 },
			38: {"__id__": 38, "skill": [1261, 1262], "ban": [], "level": 4, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 25, "wine": 21, "book": 29 },
			39: {"__id__": 39, "skill": [1121], "ban": [], "level": 4, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 28, "book": 22 },
			40: {"__id__": 40, "skill": [1212], "ban": [], "level": 4, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 26, "wine": 30, "book": 20 },
			41: {"__id__": 41, "skill": [1331, 1332, 1333], "ban": [1, 26, 32, 44, 54, 59], "level": 4, "min_single": 4, "max_single": 7, "min_total": 22, "max_total": 30, "wine": 36, "book": 14 },
			42: {"__id__": 42, "skill": [1241, 1242, 1243], "ban": [], "level": 4, "min_single": 5, "max_single": 7, "min_total": 22, "max_total": 32, "wine": 10, "book": 40 },
			43: {"__id__": 43, "skill": [1481], "ban": [], "level": 4, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 25, "wine": 18, "book": 32 },
			44: {"__id__": 44, "skill": [1371, 1372], "ban": [6, 13, 41], "level": 4, "min_single": 2, "max_single": 5, "min_total": 10, "max_total": 20, "wine": 22, "book": 28 },
			45: {"__id__": 45, "skill": [1431], "ban": [4, 12, 20, 23, 24, 36, 37, 55, 60], "level": 4, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 25, "wine": 36, "book": 14 },
			46: {"__id__": 46, "skill": [1021], "ban": [], "level": 4, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 26, "book": 24 },
			47: {"__id__": 47, "skill": [1012], "ban": [], "level": 4, "min_single": 2, "max_single": 6, "min_total": 10, "max_total": 20, "wine": 12, "book": 38 },
			48: {"__id__": 48, "skill": [1391], "ban": [], "level": 4, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 21, "wine": 26, "book": 24 },
			49: {"__id__": 49, "skill": [1462], "ban": [], "level": 5, "min_single": 2, "max_single": 6, "min_total": 10, "max_total": 20, "wine": 42, "book": 18 },
			50: {"__id__": 50, "skill": [1311], "ban": [], "level": 5, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 24, "wine": 38, "book": 22 },
			51: {"__id__": 51, "skill": [1116], "ban": [], "level": 5, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 25, "wine": 42, "book": 18 },
			52: {"__id__": 52, "skill": [1361, 1362], "ban": [], "level": 5, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 26, "wine": 28, "book": 32 },
			53: {"__id__": 53, "skill": [1213], "ban": [], "level": 5, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 26, "wine": 26, "book": 34 },
			54: {"__id__": 54, "skill": [1194, 1195], "ban": [6, 13, 41], "level": 5, "min_single": 2, "max_single": 6, "min_total": 10, "max_total": 20, "wine": 12, "book": 48 },
			55: {"__id__": 55, "skill": [1381], "ban": [45], "level": 5, "min_single": 2, "max_single": 9, "min_total": 10, "max_total": 27, "wine": 52, "book": 8 },
			56: {"__id__": 56, "skill": [1022], "ban": [], "level": 5, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 24, "wine": 18, "book": 42 },
			57: {"__id__": 57, "skill": [1181], "ban": [], "level": 5, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 21, "wine": 24, "book": 36 },
			58: {"__id__": 58, "skill": [1171], "ban": [], "level": 5, "min_single": 2, "max_single": 7, "min_total": 10, "max_total": 25, "wine": 16, "book": 44 },
			59: {"__id__": 59, "skill": [1374, 1375], "ban": [6, 13, 41], "level": 5, "min_single": 2, "max_single": 5, "min_total": 10, "max_total": 20, "wine": 14, "book": 46 },
			60: {"__id__": 60, "skill": [1971], "ban": [23, 24, 37, 45], "level": 5, "min_single": 2, "max_single": 8, "min_total": 10, "max_total": 26, "wine": 48, "book": 12 }
		}

		private static _keys = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60];

        public static get(id:number): any {
            return diy._data[id];
        }

        public static get keys() {
            return diy._keys
        }
    }
    
}
