// Generated by xls2ts.py
// DO NOT EDIT!
///<reference path="text.ts" />

module Data {

    export class exchange {

        private static _data = {
            1: {"__id__": 1, "resouce": "weapon", "buy": 200, "sold": 50 },
			2: {"__id__": 2, "resouce": "horse", "buy": 200, "sold": 50 },
			3: {"__id__": 3, "resouce": "material", "buy": 200, "sold": 50 },
			5: {"__id__": 5, "resouce": "forage", "buy": 200, "sold": 50 },
			6: {"__id__": 6, "resouce": "medicine", "buy": 2000, "sold": 500 },
			7: {"__id__": 7, "resouce": "bandage", "buy": 200, "sold": 50 },
			8: {"__id__": 8, "resouce": "wine", "buy": 200, "sold": 50 },
			9: {"__id__": 9, "resouce": "book", "buy": 200, "sold": 50 }
		}

		private static _keys = [1, 2, 3, 5, 6, 7, 8, 9];

        public static get(id:number): any {
            return exchange._data[id];
        }

        public static get keys() {
            return exchange._keys
        }
    }
    
}
