// Generated by xls2ts.py
// DO NOT EDIT!
///<reference path="text.ts" />

module Data {

    export class redframe {

        private static _data = {
            1: {"__id__": 1, "weapon": "knife", "frame": 4, "sound": "knife" },
			2: {"__id__": 2, "weapon": "gun", "frame": 5, "sound": "gun" },
			3: {"__id__": 3, "weapon": "finger", "frame": 3, "sound": "finger" },
			4: {"__id__": 4, "weapon": "arrow", "frame": 3, "sound": "arrow" },
			5: {"__id__": 5, "weapon": "hammer", "frame": 3, "sound": "hammer" },
			6: {"__id__": 6, "weapon": "lighting", "frame": 1, "sound": "lighting" },
			7: {"__id__": 7, "weapon": "stone", "frame": 9, "sound": "stone" },
			8: {"__id__": 8, "weapon": "wave", "frame": 3, "sound": "wave" },
			9: {"__id__": 9, "weapon": "flower", "frame": 3, "sound": "flower" },
			10: {"__id__": 10, "weapon": "guard", "frame": 0, "sound": "guard" },
			11: {"__id__": 11, "weapon": "hook", "frame": 0, "sound": "hook" },
			12: {"__id__": 12, "weapon": "frame", "frame": 0, "sound": "frame" },
			13: {"__id__": 13, "weapon": "cable", "frame": 0, "sound": "cable" }
		}

		private static _keys = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];

        public static get(id:number): any {
            return redframe._data[id];
        }

        public static get keys() {
            return redframe._keys
        }
    }
    
}
